/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type { MenuDto } from '.././model';
import { customInstance } from '.././libs/customAxios';
import type { ErrorType } from '.././libs/customAxios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getMemus = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MenuDto[]>(
    {
      url: `http://localhost:3005/api/v1/admin/admin/menus`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetMemusQueryKey = () => {
  return [`http://localhost:3005/api/v1/admin/admin/menus`] as const;
};

export const getGetMemusQueryOptions = <
  TData = Awaited<ReturnType<typeof getMemus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMemus>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMemusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemus>>> = ({
    signal,
  }) => getMemus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMemus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMemusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMemus>>
>;
export type GetMemusQueryError = ErrorType<unknown>;

export const useGetMemus = <
  TData = Awaited<ReturnType<typeof getMemus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMemus>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetMemusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
