packages:
  - apps/*
  - packages/*

catalog:
  vite: ^6.0.8
  "@vitejs/plugin-react": ^4.7.0
  "@vitejs/plugin-react-swc": ^3.11.0
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/browser": ^3.2.4
  typescript: ~5.8.3
  "@types/node": ^24.1.0
  react: "19.0.0"
  react-dom: "19.0.0"
  "@types/react": "~19.0.10"
  "@types/react-dom": "~19.0.6"
  "@biomejs/biome": ^2.1.4
  "@heroui/react": ^2.8.2
  "@heroui/use-theme": ^2.1.10
  # 테스팅 관련
  "@testing-library/jest-dom": ^6.6.4
  "@testing-library/react": ^16.3.0
  jsdom: ^26.1.0
  # 빌드/개발 도구
  tsup: ^8.5.0
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/vite": ^4.1.11
  postcss: ^8.5.6
  autoprefixer: ^10.4.21
  # 타입 정의
  "@types/lodash-es": ^4.17.12
  "@types/uuid": ^10.0.0
  "@types/pluralize": ^0.0.33
  # 핵심 라이브러리  
  axios: ^1.11.0
  dayjs: "1.11.13"
  lodash-es: "4.17.21"
  uuid: ^11.1.0
  pluralize: ^8.0.0
  remeda: ^2.27.0
  # React 생태계
  framer-motion: ^12.23.11
  react-dropzone: ^14.3.8
  react-cookie: ^8.0.1
  # 상태관리/유틸
  mobx: ^6.13.7
  mobx-react-lite: ^4.1.0
  class-variance-authority: ^0.7.1
  lucide-react: ^0.533.0
  nuqs: ^2.4.3
  # 스토리북
  storybook: ^9.0.18
  "@storybook/addon-docs": ^9.0.18
  "@storybook/react-vite": ^9.0.18

onlyBuiltDependencies:
  - '@nestjs/core'
  - nestjs-pino
