packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.1.4
  '@tanstack/react-query': 5.83.0
  '@heroui/react': ^2.8.2
  '@heroui/use-theme': ^2.1.10
  '@prisma/client': ^6.11.1
  '@storybook/addon-docs': ^9.0.18
  '@storybook/react-vite': ^9.0.18
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.1
  '@types/pluralize': ^0.0.33
  '@types/react': ~19.0.10
  '@types/react-dom': ~19.0.6
  '@types/uuid': 10.0.0
  '@vitejs/plugin-react': ^4.7.0
  '@vitejs/plugin-react-swc': ^3.11.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  autoprefixer: ^10.4.21
  axios: ^1.11.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dayjs: 1.11.18
  framer-motion: ^12.23.11
  jsdom: ^26.1.0
  lodash-es: 4.17.21
  lucide-react: ^0.533.0
  mobx: 6.13.7
  mobx-react-lite: 4.1.0
  nuqs: ^2.4.3
  pluralize: ^8.0.0
  postcss: ^8.5.6
  prisma: 6.11.1
  react: 19.0.0
  react-cookie: ^8.0.1
  react-dom: 19.0.0
  react-dropzone: ^14.3.8
  remeda: ^2.30.0
  storybook: ^9.1.1
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  typescript: ^5.9.2
  uuid: ^11.1.0
  vite: ^6.0.8
  vitest: ^3.2.4

ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - '@nestjs/core'
  - nestjs-pino
