import {
  CATEGORIES_PAGE_PATH,
  CATEGORY_EDIT_PAGE_PATH,
  CATEGORY_ITEMS_PAGE_PATH,
  CATEGORY_ITEM_EDIT_PAGE_PATH,
  CATEGORY_PAGE_PATH,
  GROUPS_PAGE_PATH,
  GROUP_EDIT_PAGE_PATH,
  GROUP_PAGE_PATH,
  LOGIN_PAGE_PATH,
  SERVICES_PAGE_PATH,
  SERVICE_EDIT_PAGE_PATH,
  SERVICE_PAGE_PATH,
  USERS_PAGE_PATH,
  USER_EDIT_PAGE_PATH,
  USER_PAGE_PATH,
  SPACES_PAGE_PATH,
  SPACE_EDIT_PAGE_PATH,
  SPACE_PAGE_PATH,
  ROLE_EDIT_PAGE_PATH,
  ROLES_PAGE_PATH,
  ROLE_PAGE_PATH,
  SESSIONS_PAGE_PATH,
  SESSION_PAGE_PATH,
  SESSION_EDIT_PAGE_PATH,
  TIMELINES_PAGE_PATH,
  TIMELINE_EDIT_PAGE_PATH,
  TIMELINE_PAGE_PATH,
  TIMELINEITEMS_PAGE_PATH,
  TIMELINEITEM_EDIT_PAGE_PATH,
  TIMELINEITEM_PAGE_PATH,
} from '@constants';

export const ADMIN_PATH = '/admin' as const;
export const DASHBOARD_PAGE_PATH = `${ADMIN_PATH}/dashboard` as const;
export type Paths =
  | typeof LOGIN_PAGE_PATH
  | typeof USERS_PAGE_PATH
  | typeof USER_PAGE_PATH
  | typeof USER_EDIT_PAGE_PATH
  | typeof SPACES_PAGE_PATH
  | typeof SPACE_PAGE_PATH
  | typeof SPACE_EDIT_PAGE_PATH
  | typeof CATEGORY_EDIT_PAGE_PATH
  | typeof CATEGORY_PAGE_PATH
  | typeof CATEGORIES_PAGE_PATH
  | typeof CATEGORY_ITEMS_PAGE_PATH
  | typeof CATEGORY_ITEM_EDIT_PAGE_PATH
  | typeof SERVICES_PAGE_PATH
  | typeof SERVICE_PAGE_PATH
  | typeof SERVICE_EDIT_PAGE_PATH
  | typeof GROUPS_PAGE_PATH
  | typeof GROUP_EDIT_PAGE_PATH
  | typeof GROUP_PAGE_PATH
  | typeof ROLE_EDIT_PAGE_PATH
  | typeof ROLES_PAGE_PATH
  | typeof ROLE_PAGE_PATH
  | typeof SESSIONS_PAGE_PATH
  | typeof SESSION_PAGE_PATH
  | typeof SESSION_EDIT_PAGE_PATH
  | typeof TIMELINES_PAGE_PATH
  | typeof TIMELINE_EDIT_PAGE_PATH
  | typeof TIMELINE_PAGE_PATH
  | typeof TIMELINEITEMS_PAGE_PATH
  | typeof TIMELINEITEM_EDIT_PAGE_PATH
  | typeof TIMELINEITEM_PAGE_PATH
  | typeof DASHBOARD_PAGE_PATH;
