import {
  CATEGORIES_PAGE_PATH,
  CATEGORY_EDIT_PAGE_PATH,
  CATEGORY_ITEMS_PAGE_PATH,
  CATEGORY_ITEM_EDIT_PAGE_PATH,
  CATEGORY_PAGE_PATH,
  GROUPS_PAGE_PATH,
  GROUP_EDIT_PAGE_PATH,
  GROUP_PAGE_PATH,
  LOGIN_PAGE_PATH,
  SERVICES_PAGE_PATH,
  SERVICE_EDIT_PAGE_PATH,
  SERVICE_PAGE_PATH,
  USERS_PAGE_PATH,
  USER_EDIT_PAGE_PATH,
  USER_PAGE_PATH,
  WORKSPACES_PAGE_PATH,
  WORKSPACE_EDIT_PAGE_PATH,
  WORKSPACE_PAGE_PATH,
} from '@constants';

export const DASHBOARD_PATH = '/admin' as const;

export type Paths =
  | typeof LOGIN_PAGE_PATH
  | typeof USERS_PAGE_PATH
  | typeof USER_PAGE_PATH
  | typeof USER_EDIT_PAGE_PATH
  | typeof WORKSPACES_PAGE_PATH
  | typeof WORKSPACE_PAGE_PATH
  | typeof WORKSPACE_EDIT_PAGE_PATH
  | typeof CATEGORY_EDIT_PAGE_PATH
  | typeof CATEGORY_PAGE_PATH
  | typeof CATEGORIES_PAGE_PATH
  | typeof CATEGORY_ITEMS_PAGE_PATH
  | typeof CATEGORY_ITEM_EDIT_PAGE_PATH
  | typeof SERVICES_PAGE_PATH
  | typeof SERVICE_PAGE_PATH
  | typeof SERVICE_EDIT_PAGE_PATH
  | typeof GROUPS_PAGE_PATH
  | typeof GROUP_EDIT_PAGE_PATH
  | typeof GROUP_PAGE_PATH;
