module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: "./src",
  testMatch: ["**/*.spec.ts", "**/*.test.ts"],
  moduleFileExtensions: ["ts", "js", "json"],
  moduleNameMapper: {
    "^@shared/schema$": "<rootDir>/../../../packages/shared-schema/src",
    "^@shared/utils$": "<rootDir>/../../../packages/shared-utils/src",
    "^@shared/vars$": "<rootDir>/../../../packages/shared-vars/src",
    "^@shared$": "<rootDir>/shared/index",
    "^@shared/(.*)$": "<rootDir>/shared/$1",
  },
  transform: {
    "^.+\\.ts$": [
      "ts-jest",
      {
        tsconfig: {
          module: "commonjs",
          target: "es2022",
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          types: ["jest", "node"],
          skipLibCheck: true,
          strict: false,
          paths: {
            "@shared": ["./shared/index"],
            "@shared/*": ["./shared/*"],
            "@shared/schema": ["../../packages/shared-schema/src"],
            "@shared/utils": ["../../packages/shared-utils/src"],
            "@shared/vars": ["../../packages/shared-vars/src"],
          },
        },
      },
    ],
  },
  setupFilesAfterEnv: ["<rootDir>/shared/test/setup.ts"],
  collectCoverageFrom: [
    "**/*.ts",
    "!**/*.spec.ts",
    "!**/*.test.ts",
    "!**/*.d.ts",
    "!**/index.ts",
    "!**/main.ts",
    "!**/main.config.ts",
  ],
  coverageDirectory: "<rootDir>/../coverage",
  coverageReporters: ["text", "lcov", "html"],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  maxWorkers: 1,
  testTimeout: 10000,
  forceExit: true,
  detectOpenHandles: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
