/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from "./abilityActions";
import type { TenantDto } from "./tenantDto";

export interface ActionDto {
	id: string;
	seq: number;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	tenantId: string;
	name: AbilityActions;
	conditions?: string;
	tenant?: TenantDto;
}
