/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryTypes } from "./categoryTypes";

export interface CategoryDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  tenantId: string;
  name: string;
  type: CategoryTypes;
  /** @nullable */
  parentId: string | null;
  parent?: CategoryDto;
  children?: CategoryDto;
}
