/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateFileDto {
	parentId: string;
	tenantId: string;
	name: string;
	size: number;
	mimeType: string;
	url: string;
}
