/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityTypes } from "./abilityTypes";

export interface CreateAbilityDto {
	tenantId: string;
	actionId: string;
	/** @nullable */
	conditions?: string | null;
	subjectId: string;
	type: AbilityTypes;
	roleId: string;
	/** @nullable */
	description?: string | null;
}
