/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { CreateSessionDtoRecurringDayOfWeek } from "./createSessionDtoRecurringDayOfWeek";
import type { CreateSessionDtoRepeatCycleType } from "./createSessionDtoRepeatCycleType";
import type { SessionTypes } from "./sessionTypes";

export interface CreateSessionDto {
	name: string;
	label: string;
	startDateTime?: string;
	endDateTime?: string;
	/** @nullable */
	timelineId?: string | null;
	/** @nullable */
	repeatCycleType?: CreateSessionDtoRepeatCycleType;
	/** @nullable */
	recurringDayOfWeek?: CreateSessionDtoRecurringDayOfWeek;
	/** @nullable */
	recurringMonth?: number | null;
	type: SessionTypes;
}
