/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ActionDto } from "./actionDto";

export type CreateAction200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	/** @nullable */
	data?: ActionDto;
};
