/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateWorkspaceDto } from './createWorkspaceDto';

export interface CreateGroundDto {
  /** @nullable */
  imageDepotId?: string | null;
  workspace: CreateWorkspaceDto;
}
