/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from "./tenantDto";

export type CreateTenant200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	/** @nullable */
	data?: TenantDto;
};
