/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from './tenantDto';
import type { FileClassificationDto } from './fileClassificationDto';

export interface FileDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  tenantId: string;
  name: string;
  depotId: string;
  size: number;
  mimeType: string;
  url: string;
  tenant?: TenantDto;
  classification?: FileClassificationDto;
}
