/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export type GetCurrentSpace200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  /** @nullable */
  data?: SpaceDto;
};
