/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroundDto } from './groundDto';
import type { GetGroundsByUserId200AllOfMeta } from './getGroundsByUserId200AllOfMeta';

export type GetGroundsByUserId200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GroundDto[];
  meta?: GetGroundsByUserId200AllOfMeta;
};
