/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Order } from "./order";

export type GetGroupsByQueryParams = {
	skip?: number;
	take?: number;
	name?: string;
	serviceId?: string;
	orderByCreatedAt?: Order;
};
