/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroundDto } from './groundDto';
import type { GetGroundsByQuery200AllOfMeta } from './getGroundsByQuery200AllOfMeta';

export type GetGroundsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GroundDto[];
  meta?: GetGroundsByQuery200AllOfMeta;
};
