/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { GetMyTenants200AllOfMeta } from "./getMyTenants200AllOfMeta";
import type { TenantDto } from "./tenantDto";

export type GetMyTenants200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: TenantDto[];
	meta?: GetMyTenants200AllOfMeta;
};
