/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type GetManyByQueryParams = {
/**
 * Number of records to skip for pagination
 */
skip?: number;
/**
 * Number of records to take for pagination
 */
take?: number;
};
