/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { GetRoutinesByQuery200AllOfMeta } from "./getRoutinesByQuery200AllOfMeta";
import type { RoutineDto } from "./routineDto";

export type GetRoutinesByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: RoutineDto[];
  meta?: GetRoutinesByQuery200AllOfMeta;
};
