/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceClassificationDto } from './spaceClassificationDto';
import type { GetSpaceClassificationsByQuery200AllOfMeta } from './getSpaceClassificationsByQuery200AllOfMeta';

export type GetSpaceClassificationsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: SpaceClassificationDto[];
  meta?: GetSpaceClassificationsByQuery200AllOfMeta;
};
