/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { GetSessionsByQuery200AllOfMeta } from "./getSessionsByQuery200AllOfMeta";
import type { SessionDto } from "./sessionDto";

export type GetSessionsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: SessionDto[];
  meta?: GetSessionsByQuery200AllOfMeta;
};
