/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { GetTenantsByQuery200AllOfMeta } from "./getTenantsByQuery200AllOfMeta";
import type { TenantDto } from "./tenantDto";

export type GetTenantsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: TenantDto[];
  meta?: GetTenantsByQuery200AllOfMeta;
};
