/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetTenantsByQueryParams = {
skip?: number;
take?: number;
createdAtSortOrder?: SortOrder;
};
