/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { GetUsersByQuery200AllOfMeta } from './getUsersByQuery200AllOfMeta';

export type GetUsersByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: UserDto[];
  meta?: GetUsersByQuery200AllOfMeta;
};
