/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { GetUsersByQuery200AllOfMeta } from "./getUsersByQuery200AllOfMeta";
import type { UserDto } from "./userDto";

export type GetUsersByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: UserDto[];
	meta?: GetUsersByQuery200AllOfMeta;
};
