/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { GroundDtoSpace } from './groundDtoSpace';

export interface GroundDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  /** @nullable */
  label?: string | null;
  address: string;
  phone: string;
  email: string;
  businessNo: string;
  /** @nullable */
  logoImageFileId?: string | null;
  /** @nullable */
  imageFileId?: string | null;
  spaceId: string;
  /** @nullable */
  space?: GroundDtoSpace;
}
