/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroupTypes } from "./groupTypes";
import type { TenantDto } from "./tenantDto";

export interface GroupDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  /** @nullable */
  label?: string | null;
  type: GroupTypes;
  tenantId: string;
  tenant?: TenantDto;
}
