/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroundDtoWorkspace } from './groundDtoWorkspace';
import type { GroundDtoImageDepot } from './groundDtoImageDepot';

export interface GroundDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  imageDepotId?: string | null;
  /** @nullable */
  workspaceId?: string | null;
  /** @nullable */
  workspace?: GroundDtoWorkspace;
  /** @nullable */
  imageDepot?: GroundDtoImageDepot;
}
