/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { DepotDto } from './depotDto';
import type { SpaceDto } from './spaceDto';

export interface GymDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  label?: string;
  businessNo: string;
  spaceId: string;
  address: string;
  phone: string;
  email: string;
  depotId: string;
  depot?: DepotDto;
  space?: SpaceDto;
}
