/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceNames = typeof ServiceNames[keyof typeof ServiceNames];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceNames = {
  user: 'user',
  role: 'role',
  space: 'space',
  timeline: 'timeline',
  file: 'file',
  task: 'task',
  program: 'program',
} as const;
