/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfWeek } from './recurringDayOfWeek';

/**
 * @nullable
 */
export type SessionDtoRecurringDayOfWeek = RecurringDayOfWeek | null;
