/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpPayloadDto {
  nickname: string;
  spaceId: string;
  email: string;
  name: string;
  phone: string;
  password: string;
}
