/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

import type { RoleDto } from "./roleDto";
import type { SpaceDto } from "./spaceDto";
import type { UserDto } from "./userDto";

export interface TenantDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  main: boolean;
  roleId: string;
  userId: string;
  spaceId: string;
  user?: UserDto;
  space?: SpaceDto;
  role?: RoleDto;
}
