/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserDto {
  spaceId?: string;
  email?: string;
  name?: string;
  phone?: string;
  /**
   * 응답 제외 필드
   * @minLength 6
   */
  password?: string;
}
