/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from "./abilityActions";

export interface UpdateActionDto {
	tenantId?: string;
	name?: AbilityActions;
	conditions?: string;
}
