/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProgramDto {
	instructorId?: string;
	capacity?: number;
	routineId?: string;
	sessionId?: string;
	tenancyId?: string;
}
