/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateGroundDto {
	name?: string;
	/** @nullable */
	label?: string | null;
	address?: string;
	phone?: string;
	email?: string;
	businessNo?: string;
	/** @nullable */
	logoImageFileId?: string | null;
	/** @nullable */
	imageFileId?: string | null;
	spaceId?: string;
}
