/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { FileClassificationDto } from './fileClassificationDto';

export type UpdateFileClassification200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  /** @nullable */
  data?: FileClassificationDto;
};
