/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTenantDto {
  main?: boolean;
  roleId?: string;
  userId?: string;
  spaceId?: string;
}
