/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SessionTypes } from "./sessionTypes";
import type { UpdateSessionDtoRecurringDayOfWeek } from "./updateSessionDtoRecurringDayOfWeek";
import type { UpdateSessionDtoRepeatCycleType } from "./updateSessionDtoRepeatCycleType";

export interface UpdateSessionDto {
	id?: string;
	seq?: number;
	createdAt?: string;
	updatedAt?: string;
	/** @nullable */
	removedAt?: string | null;
	name?: string;
	label?: string;
	type?: SessionTypes;
	startDateTime?: string;
	endDateTime?: string;
	/** @nullable */
	timelineId?: string | null;
	/** @nullable */
	repeatCycleType?: UpdateSessionDtoRepeatCycleType;
	/** @nullable */
	recurringDayOfWeek?: UpdateSessionDtoRecurringDayOfWeek;
	/** @nullable */
	recurringMonth?: number | null;
}
