/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateExerciseDto {
	name?: string;
	description?: string;
	imageFileId?: string;
	videoFileId?: string;
	duration?: number;
	count?: number;
	tenantId?: string;
}
