/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceClassificationDto } from './spaceClassificationDto';

export type UpdateSpaceClassification200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  /** @nullable */
  data?: SpaceClassificationDto;
};
