/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface WorkspaceDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  label?: string | null;
  /** 작업공간명 */
  name: string;
  /** 작업공간 주소 */
  address: string;
  /** 전화번호 */
  phone: string;
  /** 이메일 */
  email: string;
  /** 사업자등록번호 */
  businessNo: string;
  /**
   * 로고 이미지 ID
   * @nullable
   */
  logoImageDepotId?: string | null;
  /** 작업공간 ID */
  spaceId: string;
}
