import {
  AuthModule,
  CategoriesModule,
  CategoryItemsModule,
  GroupsModule,
  LoggerModule,
  PrismaModule,
  ProfilesModule,
  ReservationsModule,
  RolesModule,
  ServicesModule,
  SessionsModule,
  SpacesModule,
  TenantsModule,
  TimelineItemsModule,
  TimelinesModule,
  UsersModule,
} from '../modules';

export const appModules = [
  AuthModule,
  CategoriesModule,
  CategoryItemsModule,
  GroupsModule,
  LoggerModule,
  PrismaModule,
  ProfilesModule,
  ReservationsModule,
  RolesModule,
  ServicesModule,
  SessionsModule,
  SpacesModule,
  TenantsModule,
  TimelineItemsModule,
  TimelinesModule,
  UsersModule,
];
