export default {
  entry: ["src/index.ts"],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  splitting: false,
  sourcemap: true,
  minify: false,
  external: [
    "@nestjs/common",
    "@nestjs/core",
    "@nestjs/config",
    "@nestjs/jwt",
    "@nestjs/passport",
    "@nestjs/platform-express",
    "@nestjs/swagger",
    "@nestjs/mapped-types",
    "@nestjs/terminus",
    "@nestjs/throttler",
    "@casl/ability",
    "@casl/prisma",
    "@shared/prisma",
    "@shared/backend",
    "@prisma/client",
    "@aws-sdk/client-s3",
    "@shared/utils",
    "@shared/vars",
    "@shared/types",
    "axios",
    "bcrypt",
    "class-transformer",
    "class-validator",
    "dayjs",
    "express",
    "lodash",
    "libphonenumber-js",
    "nest-casl",
    "nestjs-cls",
    "nestjs-pino",
    "nestjs-prisma",
    "passport",
    "passport-jwt",
    "passport-local",
    "pino",
    "pino-http",
    "reflect-metadata",
    "remeda",
    "rxjs",
    "ts-jenum",
    "uuid"
  ],
};
