/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityOrderBy } from './abilityOrderBy';
import type { AbilityWhere } from './abilityWhere';

export interface AbilityPageQuery {
  orderBy?: AbilityOrderBy;
  /** @minimum 1 */
  page?: number;
  /**
   * @minimum 1
   * @maximum 50
   */
  take?: number;
  where?: AbilityWhere;
}
