/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from './abilityActions';
import type { AbilityDtoConditions } from './abilityDtoConditions';
import type { AbilityTypes } from './abilityTypes';

export interface AbilityDto {
  action: AbilityActions;
  /** A JSON object with a nested structure */
  conditions?: AbilityDtoConditions;
  createdAt: string;
  description?: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  roleId: string;
  subjectId: string;
  type: AbilityTypes;
  updatedAt: string;
}
