/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityTypes } from './abilityTypes';

export interface AbilityDto {
  actionId: string;
  /** @nullable */
  conditions?: string | null;
  createdAt: string;
  /** @nullable */
  description?: string | null;
  id: string;
  /** @nullable */
  removedAt: string | null;
  roleId: string;
  seq: number;
  subjectId: string;
  tenancyId: string;
  type: AbilityTypes;
  updatedAt: string;
}
