/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type AbilityTypes = typeof AbilityTypes[keyof typeof AbilityTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbilityTypes = {
  CAN: 'CAN',
  CAN_NOT: 'CAN_NOT',
} as const;
