/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type AbilityActions = typeof AbilityActions[keyof typeof AbilityActions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbilityActions = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ACCESS: 'ACCESS',
} as const;
