/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export interface AbilityOrderBy {
  action?: SortOrder;
  conditions?: SortOrder;
  createdAt?: SortOrder;
  deletedAt?: SortOrder;
  description?: SortOrder;
  id?: SortOrder;
  roleId?: SortOrder;
  subjectId?: SortOrder;
  type?: SortOrder;
  updatedAt?: SortOrder;
}
