/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from './abilityActions';
import type { AbilityDtoConditions } from './abilityDtoConditions';
import type { AbilityTypes } from './abilityTypes';

export interface AbilityDto {
  action: AbilityActions;
  /**
   * A JSON object with a nested structure
   * @nullable
   */
  conditions: AbilityDtoConditions;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  description?: string;
  id: string;
  roleId: string;
  subjectId: string;
  type: AbilityTypes;
  updatedAt: string;
}
