/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from './abilityActions';

export interface ActionDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  tenancyId: string;
  name: AbilityActions;
  conditions?: string;
}
