/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';

export interface AssignmentDto {
  createdAt: string;
  group?: GroupDto;
  /** @nullable */
  groupId: string | null;
  id: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  updatedAt: string;
}
