/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface AssignmentDto {
  createdAt: string;
  groupId: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  serviceId: string;
  serviceItemId: string;
  updatedAt: string;
}
