/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface AssociationDto {
  createdAt: string;
  /** @nullable */
  groupId?: string | null;
  id: string;
  /** @nullable */
  postId?: string | null;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  serviceId: string;
  /** @nullable */
  spaceId?: string | null;
  tenancyId: string;
  updatedAt: string;
  /** @nullable */
  userId?: string | null;
}
