/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { ServiceDto } from './serviceDto';
import type { TenancyDto } from './tenancyDto';
import type { CategoryTypes } from './categoryTypes';

export interface CategoryDto {
  children?: CategoryDto;
  classifications?: ClassificationDto;
  createdAt: string;
  id: string;
  name: string;
  parent?: CategoryDto;
  /** @nullable */
  parentId: string | null;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  service?: ServiceDto;
  serviceId: string;
  tenancy?: TenancyDto;
  tenancyId: string;
  type: CategoryTypes;
  updatedAt: string;
}
