/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type CategoryTypes = typeof CategoryTypes[keyof typeof CategoryTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryTypes = {
  LEAF: 'LEAF',
  ROOT: 'ROOT',
} as const;
