/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type CategoryTypes = typeof CategoryTypes[keyof typeof CategoryTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryTypes = {
  USER: 'USER',
  SPACE: 'SPACE',
  DEPOT_FILE: 'DEPOT_FILE',
  POST: 'POST',
} as const;
