/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CategoryDto {
  ancestorIds: string[];
  createdAt: string;
  id: string;
  name: string;
  /** @nullable */
  parentId: string | null;
  /** @nullable */
  removedAt: string | null;
  serviceId: string;
  tenantId: string;
  updatedAt: string;
}
