/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Boolean } from './boolean';

export type CheckEmailVerification200AllOf = {
  data?: Boolean;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
