/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Boolean } from './boolean';
import type { CheckEmailVerification200AllOfMeta } from './checkEmailVerification200AllOfMeta';

export type CheckEmailVerification200AllOf = {
  data?: Boolean;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CheckEmailVerification200AllOfMeta;
};
