/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { SpaceDto } from './spaceDto';
import type { TenancyDto } from './tenancyDto';
import type { UserDto } from './userDto';

export interface ClassificationDto {
  category?: CategoryDto;
  categoryId: string;
  createdAt: string;
  id: string;
  /** @nullable */
  postId: string | null;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  roleId: string | null;
  seq: number;
  serviceId: string;
  /** @nullable */
  spaceId: string | null;
  spaces?: SpaceDto;
  tenancy?: TenancyDto;
  tenancyId: string;
  updatedAt: string;
  /** @nullable */
  userId: string | null;
  users?: UserDto;
}
