/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { SpaceDto } from './spaceDto';
import type { UserDto } from './userDto';

export interface ClassificationDto {
  category?: CategoryDto;
  categoryId: string;
  createdAt: string;
  /** @nullable */
  depotFileId: string | null;
  id: string;
  /** @nullable */
  postId: string | null;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  space?: SpaceDto;
  /** @nullable */
  spaceId: string | null;
  updatedAt: string;
  user?: UserDto;
  /** @nullable */
  userId: string | null;
}
