/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';

export interface ClassificationDto {
  category?: CategoryDto;
  categoryId: string;
  createdAt: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  updatedAt: string;
}
