/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ContentDtoType } from './contentDtoType';

export interface ContentDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  depotId: string | null;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  type: ContentDtoType;
  text?: string;
  tenantId: string;
}
