/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TextTypes } from './textTypes';

/**
 * @nullable
 */
export type ContentDtoType = TextTypes | null;
