/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAssignmentDto } from './createAssignmentDto';

export interface CreateAssignmentDtos {
  items: CreateAssignmentDto[];
}
