/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSignUpPayloadDtoProfileCreatedAt } from './createSignUpPayloadDtoProfileCreatedAt';
import type { CreateSignUpPayloadDtoProfileDeletedAt } from './createSignUpPayloadDtoProfileDeletedAt';
import type { CreateSignUpPayloadDtoProfileUpdatedAt } from './createSignUpPayloadDtoProfileUpdatedAt';

export type CreateSignUpPayloadDtoProfile = {
  createdAt: CreateSignUpPayloadDtoProfileCreatedAt;
  deletedAt?: CreateSignUpPayloadDtoProfileDeletedAt;
  id: string;
  nickname: string;
  updatedAt?: CreateSignUpPayloadDtoProfileUpdatedAt;
  userId: string;
};
