/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimelineItemDto {
  address: string;
  endDateTime: string;
  maxCapacity: number;
  minCapacity: number;
  sessionId: string;
  startDateTime: string;
  tenantId: string;
  title: string;
}
