/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRoutineDto } from './createRoutineDto';
import type { CreateRoutineBodyAllOf } from './createRoutineBodyAllOf';

export type CreateRoutineBody = CreateRoutineDto & CreateRoutineBodyAllOf;
