/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TenancyDto } from './tenancyDto';
import type { CreateSpace200AllOfMeta } from './createSpace200AllOfMeta';

export type CreateSpace200AllOf = {
  data?: TenancyDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateSpace200AllOfMeta;
};
