/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type CreateServiceDtoName = typeof CreateServiceDtoName[keyof typeof CreateServiceDtoName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateServiceDtoName = {
  USER: 'USER',
  SPACE: 'SPACE',
  SETTING: 'SETTING',
} as const;
