/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';

export interface CreateRoleDto {
  name: Roles;
  tenancyId: string;
  serviceId: string;
  categoryId: string;
}
