/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContentDto } from './createContentDto';

export interface CreateTaskDto {
  tenantId: string;
  content: CreateContentDto;
}
