/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Object } from './object';

export type CreateUserAssociation200AllOf = {
  data?: Object;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
