/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { CreateUser200AllOfMeta } from './createUser200AllOfMeta';

export type CreateUser200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateUser200AllOfMeta;
};
