/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimelineDto {
  endDateTime: string;
  name: string;
  startDateTime: string;
  tenancyId: string;
  tenantId: string;
}
