/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PostTypes } from './postTypes';

export interface CreatePostDto {
  assignemntIds: string[];
  authorId: string;
  classificationId: string;
  content: string;
  description?: string;
  dopotId: string;
  spaceId: string;
  title: string;
  type: PostTypes;
}
