/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContentDtoType } from './createContentDtoType';

export interface CreateContentDto {
  /** @nullable */
  depotId: string | null;
  /** @nullable */
  title: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  type: CreateContentDtoType;
  text?: string;
  tenantId: string;
}
