/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { CreateAssociations200AllOfMeta } from './createAssociations200AllOfMeta';

export type CreateAssociations200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateAssociations200AllOfMeta;
};
