/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';

export type CreateSession200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
