/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';

export type CreateAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
