/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityActions } from './abilityActions';

export interface CreateActionDto {
  tenancyId: string;
  name: AbilityActions;
  conditions?: string;
}
