/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserDto {
  email: string;
  name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  spaceId: string;
  tenancyId: string;
}
