/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TextTypes } from './textTypes';

export interface CreateContentDto {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  dopotId?: string | null;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type: TextTypes;
}
