/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SystemEmailDto } from './systemEmailDto';
import type { CreateTemplate200AllOfMeta } from './createTemplate200AllOfMeta';

export type CreateTemplate200AllOf = {
  data?: SystemEmailDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateTemplate200AllOfMeta;
};
