/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityTypes } from './abilityTypes';

export interface CreateAbilityDto {
  tenancyId: string;
  actionId: string;
  /** @nullable */
  conditions?: string | null;
  subjectId: string;
  type: AbilityTypes;
  roleId: string;
  /** @nullable */
  description?: string | null;
}
