/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSpaceDto {
  associationIds: string[];
  /** @nullable */
  classificationId: string | null;
  name: string;
}
