/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineDto } from './timelineDto';

export type CreateTimeline200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: TimelineDto;
};
