/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRoutineDtoType } from './createRoutineDtoType';

export interface CreateRoutineDto {
  name: string;
  tenancyId: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  type: CreateRoutineDtoType;
  /** @nullable */
  text?: string | null;
}
