/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGymDto {
  spaceId: string;
  address: string;
  phone: string;
  email: string;
  businessNumber: string;
  depotId: string;
}
