/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCategoryDto {
  ancestorIds: string[];
  name: string;
  /** @nullable */
  parentId: string | null;
  serviceId: string;
  tenantId: string;
}
