/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateClassificationDto {
  tenancyId: string;
  /** @nullable */
  userId: string | null;
  /** @nullable */
  postId: string | null;
  /** @nullable */
  spaceId: string | null;
  /** @nullable */
  roleId: string | null;
  categoryId: string;
  serviceId: string;
}
