/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { CreateAssociation200AllOfMeta } from './createAssociation200AllOfMeta';

export type CreateAssociation200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateAssociation200AllOfMeta;
};
