/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateServiceDtoName } from './createServiceDtoName';

export interface CreateServiceDto {
  /** @nullable */
  label: string | null;
  name: CreateServiceDtoName;
}
