/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { CreateCategory200AllOfMeta } from './createCategory200AllOfMeta';

export type CreateCategory200AllOf = {
  data?: CategoryDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateCategory200AllOfMeta;
};
