/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateFileDto {
  tenantId: string;
  name: string;
  depotId: string;
  size: number;
  mimeType: string;
  url: string;
}
