/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';

export type CreateCategory200AllOf = {
  data?: CategoryDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
