/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePageDto {
  elementIds: string;
  name: string;
  /** @nullable */
  params?: string | null;
  pathname: string;
  tenantId: string;
}
