/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClassificationDto } from './createClassificationDto';

export interface CreateClassificationDtos {
  items: CreateClassificationDto;
}
