/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserDto {
  email: string;
  name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
}
