/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceName } from './serviceName';

export interface CreateServiceDto {
  /** @nullable */
  label: string | null;
  name: ServiceName;
}
