/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { CreateAssignment200AllOfMeta } from './createAssignment200AllOfMeta';

export type CreateAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateAssignment200AllOfMeta;
};
