/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { CreateService201AllOfMeta } from './createService201AllOfMeta';

export type CreateService201AllOf = {
  data?: ServiceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateService201AllOfMeta;
};
