/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PostTypes } from './postTypes';

export interface CreatePostDto {
  authorId: string;
  content: string;
  title: string;
  type: PostTypes;
}
