/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSignUpPayloadDtoProfile } from './createSignUpPayloadDtoProfile';
import type { CreateSignUpPayloadDtoUser } from './createSignUpPayloadDtoUser';

export interface CreateSignUpPayloadDto {
  profile: CreateSignUpPayloadDtoProfile;
  user: CreateSignUpPayloadDtoUser;
}
