/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryTypes } from './categoryTypes';

export interface CreateCategoryDto {
  name: string;
  /** @nullable */
  parentId: string | null;
  serviceId: string;
  tenantId: string;
  type: CategoryTypes;
}
