/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { SessionTypes } from './sessionTypes';

export interface CreateSessionDto {
  baseDate: string;
  endDateTime: string;
  endTime: string;
  name: string;
  recurringDayOfTheWeek: RecurringDayOfTheWeek;
  repeatCycle: number;
  repeatCycleType: RepeatCycleTypes;
  startDateTime: string;
  startTime: string;
  timelineId: string;
  type: SessionTypes;
}
