/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';
import type { CreatePage200AllOfMeta } from './createPage200AllOfMeta';

export type CreatePage200AllOf = {
  data?: PageDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreatePage200AllOfMeta;
};
