/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSignUpPayloadDtoUserCreatedAt } from './createSignUpPayloadDtoUserCreatedAt';
import type { CreateSignUpPayloadDtoUserDeletedAt } from './createSignUpPayloadDtoUserDeletedAt';
import type { CreateSignUpPayloadDtoUserUpdatedAt } from './createSignUpPayloadDtoUserUpdatedAt';

export type CreateSignUpPayloadDtoUser = {
  createdAt: CreateSignUpPayloadDtoUserCreatedAt;
  deletedAt?: CreateSignUpPayloadDtoUserDeletedAt;
  email: string;
  id: string;
  name: string;
  password: string;
  phone: string;
  updatedAt?: CreateSignUpPayloadDtoUserUpdatedAt;
};
