/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';
import type { CreateAbility201AllOfMeta } from './createAbility201AllOfMeta';

export type CreateAbility201AllOf = {
  data?: AbilityDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateAbility201AllOfMeta;
};
