/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { CreateTimelineItem200AllOfMeta } from './createTimelineItem200AllOfMeta';

export type CreateTimelineItem200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateTimelineItem200AllOfMeta;
};
