/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineDto } from './timelineDto';

export type CreateTimeline200AllOf = {
  data?: TimelineDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
