/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { CreateSpace200AllOfMeta } from './createSpace200AllOfMeta';

export type CreateSpace200AllOf = {
  data?: SpaceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: CreateSpace200AllOfMeta;
};
