/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { SessionTypes } from './sessionTypes';

export interface CreateSessionDto {
  /** @nullable */
  baseDate: string | null;
  /** @nullable */
  endDate: string | null;
  name: string;
  oneTimeDate: string;
  recurringDayOfTheWeek: RecurringDayOfTheWeek[];
  repeatCycle: number;
  repeatCycleType: RepeatCycleTypes;
  tenancyId: string;
  tenantId: string;
  timelineDates: string[];
  type: SessionTypes;
}
