/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';

export type CreateAbility200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: AbilityDto;
};
