/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateFileDto {
  name: string;
  depotId: string;
  size: number;
  mimeType: string;
  url: string;
  tenancyId: string;
}
