/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimelineItemDto {
  address: string;
  description: string;
  endDateTime: string;
  maxCapacity: number;
  minCapacity: number;
  startDateTime: string;
  tenantId: string;
  timelineId?: string;
  title: string;
}
