/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { DeleteService200AllOfMeta } from './deleteService200AllOfMeta';

export type DeleteService200AllOf = {
  data?: ServiceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteService200AllOfMeta;
};
