/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { DeleteUser200AllOfMeta } from './deleteUser200AllOfMeta';

export type DeleteUser200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteUser200AllOfMeta;
};
