/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';

export type DeleteSession200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: SessionDto;
};
