/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';
import type { DeletePage200AllOfMeta } from './deletePage200AllOfMeta';

export type DeletePage200AllOf = {
  data?: PageDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeletePage200AllOfMeta;
};
