/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';
import type { DeleteTemplate200AllOfMeta } from './deleteTemplate200AllOfMeta';

export type DeleteTemplate200AllOf = {
  data?: TemplateDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteTemplate200AllOfMeta;
};
