/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Number } from './number';

export type DeleteGroup200AllOf = {
  data?: Number;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
