/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Number } from './number';
import type { DeleteGroup200AllOfMeta } from './deleteGroup200AllOfMeta';

export type DeleteGroup200AllOf = {
  data?: Number;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteGroup200AllOfMeta;
};
