/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { DeleteTimelineItem200AllOfMeta } from './deleteTimelineItem200AllOfMeta';

export type DeleteTimelineItem200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteTimelineItem200AllOfMeta;
};
