/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { DeleteAssignment200AllOfMeta } from './deleteAssignment200AllOfMeta';

export type DeleteAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteAssignment200AllOfMeta;
};
