/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { DeleteCategory200AllOfMeta } from './deleteCategory200AllOfMeta';

export type DeleteCategory200AllOf = {
  data?: CategoryDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteCategory200AllOfMeta;
};
