/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { DeleteSpace200AllOfMeta } from './deleteSpace200AllOfMeta';

export type DeleteSpace200AllOf = {
  data?: SpaceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteSpace200AllOfMeta;
};
