/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';
import type { DeleteAbility200AllOfMeta } from './deleteAbility200AllOfMeta';

export type DeleteAbility200AllOf = {
  data?: AbilityDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteAbility200AllOfMeta;
};
