/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';
import type { DeleteSession200AllOfMeta } from './deleteSession200AllOfMeta';

export type DeleteSession200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteSession200AllOfMeta;
};
