/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';

export type DeleteSession200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
