/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { DeleteClassification200AllOfMeta } from './deleteClassification200AllOfMeta';

export type DeleteClassification200AllOf = {
  data?: ClassificationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: DeleteClassification200AllOfMeta;
};
