/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type EmailStatus = typeof EmailStatus[keyof typeof EmailStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailStatus = {
  PROGRESS: 'PROGRESS',
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  COMPLETED: 'COMPLETED',
} as const;
