/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTaskDto } from './createTaskDto';

export interface ExerciseDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  description: string;
  imageDepotId?: string;
  videoDepotId?: string;
  taskId: string;
  duration: number;
  count: number;
  task?: CreateTaskDto;
}
