/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntity } from './responseEntity';
import type { FindAllAblity200AllOf } from './findAllAblity200AllOf';

export type FindAllAblity200 = ResponseEntity & FindAllAblity200AllOf;
