/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';

export type FindByPageOptions200AllOf = {
  data?: GroupDto[];
  /** */
  message?: string;
  /** */
  statusCode?: string;
};
