/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type FindAllParams = {
page?: number;
take?: number;
id?: string;
createdAt?: string;
updatedAt?: string | null;
deletedAt?: string | null;
id?: SortOrder;
createdAt?: SortOrder;
updatedAt?: SortOrder;
deletedAt?: SortOrder;
type?: SortOrder;
roleId?: SortOrder;
action?: SortOrder;
subjectId?: SortOrder;
conditions?: SortOrder;
description?: SortOrder;
};
