/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';

export type FindAll200AllOf = {
  data?: AbilityDto[];
  /** */
  message?: string;
};
