/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { OptionDto } from './optionDto';

export interface Form {
  nameOptions: OptionDto[];
}
