/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { GetAssignmentsByQuery200AllOfMeta } from './getAssignmentsByQuery200AllOfMeta';

export type GetAssignmentsByQuery200AllOf = {
  data?: AssignmentDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAssignmentsByQuery200AllOfMeta;
};
