/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { GetAllService200AllOfMeta } from './getAllService200AllOfMeta';

export type GetAllService200AllOf = {
  data?: ServiceDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAllService200AllOfMeta;
};
