/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntity } from './responseEntity';
import type { GetAccessibleAllSpace200AllOf } from './getAccessibleAllSpace200AllOf';

export type GetAccessibleAllSpace200 = ResponseEntity & GetAccessibleAllSpace200AllOf;
