/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export type GetAccessibleSpaces200AllOf = {
  data?: SpaceDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
