/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { GetAccessibleSpaces200AllOfMeta } from './getAccessibleSpaces200AllOfMeta';

export type GetAccessibleSpaces200AllOf = {
  data?: SpaceDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAccessibleSpaces200AllOfMeta;
};
