/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';
import type { GetAbility200AllOfMeta } from './getAbility200AllOfMeta';

export type GetAbility200AllOf = {
  data?: AbilityDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAbility200AllOfMeta;
};
