/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';

export type GetAssociation200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
