/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ActionDto } from './actionDto';
import type { GetActionsByQuery200AllOfMeta } from './getActionsByQuery200AllOfMeta';

export type GetActionsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: ActionDto[];
  meta?: GetActionsByQuery200AllOfMeta;
};
