/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityTypes } from './abilityTypes';
import type { AbilityActions } from './abilityActions';
import type { SortOrder } from './sortOrder';

export type GetAbilitiesByQueryParams = {
id?: string;
createdAt?: string;
updatedAt?: string;
removedAt?: string | null;
type?: AbilityTypes;
roleId?: string;
action?: AbilityActions;
subjectId?: string;
description?: string;
typeSortOrder?: SortOrder;
roleIdSortOrder?: SortOrder;
actionSortOrder?: SortOrder;
subjectIdSortOrder?: SortOrder;
conditionsSortOrder?: SortOrder;
descriptionSortOrder?: SortOrder;
};
