/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { GetAssociation200AllOfMeta } from './getAssociation200AllOfMeta';

export type GetAssociation200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAssociation200AllOfMeta;
};
