/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export type GetAccessibleAllSpace200AllOf = {
  data?: SpaceDto[];
  /** */
  message?: string;
  /** */
  statusCode?: string;
};
