/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export type GetAccessibleSpaces200AllOf = {
  data?: SpaceDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
