/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { GetAssignment200AllOfMeta } from './getAssignment200AllOfMeta';

export type GetAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAssignment200AllOfMeta;
};
