/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ActionDto } from './actionDto';

export type GetAction200AllOf = {
  data?: ActionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
