/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { GetAssociationsByQuery200AllOfMeta } from './getAssociationsByQuery200AllOfMeta';

export type GetAssociationsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: AssociationDto[];
  meta?: GetAssociationsByQuery200AllOfMeta;
};
