/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { GetBottomTabs200AllOfMeta } from './getBottomTabs200AllOfMeta';

export type GetBottomTabs200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetBottomTabs200AllOfMeta;
};
