/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryTypes } from './categoryTypes';
import type { SortOrder } from './sortOrder';

export type GetCategoriesByQueryParams = {
skip?: number;
take?: number;
name?: string;
type?: CategoryTypes;
parentId?: string;
spaceId: string;
serviceId?: string;
nameSortOrder?: SortOrder;
};
