/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';

export type GetCategoryById200AllOf = {
  data?: CategoryDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
