/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { GetClassificationsByQuery200AllOfMeta } from './getClassificationsByQuery200AllOfMeta';

export type GetClassificationsByQuery200AllOf = {
  data?: ClassificationDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetClassificationsByQuery200AllOfMeta;
};
