/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { GetClassification200AllOfMeta } from './getClassification200AllOfMeta';

export type GetClassification200AllOf = {
  data?: ClassificationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetClassification200AllOfMeta;
};
