/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntity } from './responseEntity';
import type { GetCategories200AllOf } from './getCategories200AllOf';

export type GetCategories200 = ResponseEntity & GetCategories200AllOf;
