/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { GetClassificationsByQuery200AllOfMeta } from './getClassificationsByQuery200AllOfMeta';

export type GetClassificationsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: ClassificationDto[];
  meta?: GetClassificationsByQuery200AllOfMeta;
};
