/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';

export type GetCategories200AllOf = {
  data?: CategoryDto[];
  message?: string;
  statusCode?: string;
};
