/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { GetCategoryById200AllOfMeta } from './getCategoryById200AllOfMeta';

export type GetCategoryById200AllOf = {
  data?: CategoryDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetCategoryById200AllOfMeta;
};
