/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';

export type GetClassification200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: ClassificationDto;
};
