/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { GetCategoriesByQuery200AllOfMeta } from './getCategoriesByQuery200AllOfMeta';

export type GetCategoriesByQuery200AllOf = {
  data?: CategoryDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetCategoriesByQuery200AllOfMeta;
};
