/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { GetChildrenCategories200AllOfMeta } from './getChildrenCategories200AllOfMeta';

export type GetChildrenCategories200AllOf = {
  data?: CategoryDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetChildrenCategories200AllOfMeta;
};
