/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { DepotDto } from './depotDto';
import type { GetDepotsByQuery200AllOfMeta } from './getDepotsByQuery200AllOfMeta';

export type GetDepotsByQuery200AllOf = {
  data?: DepotDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetDepotsByQuery200AllOfMeta;
};
