/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { FileClassificationDto } from './fileClassificationDto';
import type { GetFileClassificationsByQuery200AllOfMeta } from './getFileClassificationsByQuery200AllOfMeta';

export type GetFileClassificationsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: FileClassificationDto[];
  meta?: GetFileClassificationsByQuery200AllOfMeta;
};
