/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';
import type { GetGroupsByQuery200AllOfMeta } from './getGroupsByQuery200AllOfMeta';

export type GetGroupsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GroupDto[];
  meta?: GetGroupsByQuery200AllOfMeta;
};
