/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';

export type GetGroup200AllOf = {
  data?: GroupDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
