/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GymDto } from './gymDto';
import type { GetGymsByQuery200AllOfMeta } from './getGymsByQuery200AllOfMeta';

export type GetGymsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GymDto[];
  meta?: GetGymsByQuery200AllOfMeta;
};
