/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Order } from './order';

export type GetGroupsByQueryParams = {
skip?: number;
take?: number;
name?: string;
serviceId?: string;
orderByCreatedAt?: Order;
};
