/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GymDto } from './gymDto';
import type { GetGymsByMyself200AllOfMeta } from './getGymsByMyself200AllOfMeta';

export type GetGymsByMyself200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GymDto[];
  meta?: GetGymsByMyself200AllOfMeta;
};
