/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntity } from './responseEntity';
import type { GetGroupsByPageOptions200AllOf } from './getGroupsByPageOptions200AllOf';

export type GetGroupsByPageOptions200 = ResponseEntity & GetGroupsByPageOptions200AllOf;
