/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';
import type { GetGroupsByQuery200AllOfMeta } from './getGroupsByQuery200AllOfMeta';

export type GetGroupsByQuery200AllOf = {
  data?: GroupDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetGroupsByQuery200AllOfMeta;
};
