/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleClassificationDto } from './roleClassificationDto';
import type { GetManyByQuery200AllOfMeta } from './getManyByQuery200AllOfMeta';

export type GetManyByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: RoleClassificationDto[];
  meta?: GetManyByQuery200AllOfMeta;
};
