/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { MainNavbarItemDto } from './mainNavbarItemDto';
import type { GetMainNavbarItems200AllOfMeta } from './getMainNavbarItems200AllOfMeta';

export type GetMainNavbarItems200AllOf = {
  data?: MainNavbarItemDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetMainNavbarItems200AllOfMeta;
};
