/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { MainServicePageDto } from './mainServicePageDto';
import type { GetMainServicePages200AllOfMeta } from './getMainServicePages200AllOfMeta';

export type GetMainServicePages200AllOf = {
  data?: MainServicePageDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetMainServicePages200AllOfMeta;
};
