/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GymDto } from './gymDto';
import type { GetMyGyms200AllOfMeta } from './getMyGyms200AllOfMeta';

export type GetMyGyms200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: GymDto[];
  meta?: GetMyGyms200AllOfMeta;
};
