/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramDto } from './programDto';
import type { GetProgramsByQuery200AllOfMeta } from './getProgramsByQuery200AllOfMeta';

export type GetProgramsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: ProgramDto[];
  meta?: GetProgramsByQuery200AllOfMeta;
};
