/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageTypes } from './pageTypes';
import type { SortOrder } from './sortOrder';

export type GetPagesByQueryParams = {
type?: PageTypes;
id?: string;
createdAtSortOrder?: SortOrder;
skip?: number;
take?: number;
};
