/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetPagesByQueryParams = {
skip?: number;
take?: number;
createdAtSortOrder?: SortOrder;
name?: string | null;
};
