/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';
import type { GetPagesByQuery200AllOfMeta } from './getPagesByQuery200AllOfMeta';

export type GetPagesByQuery200AllOf = {
  data?: PageDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetPagesByQuery200AllOfMeta;
};
