/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleDto } from './roleDto';

export type GetRole200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: RoleDto;
};
