/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { RouteDto } from './routeDto';
import type { GetServiceItemRoutes200AllOfMeta } from './getServiceItemRoutes200AllOfMeta';

export type GetServiceItemRoutes200AllOf = {
  data?: RouteDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetServiceItemRoutes200AllOfMeta;
};
