/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';
import type { GetSession200AllOfMeta } from './getSession200AllOfMeta';

export type GetSession200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSession200AllOfMeta;
};
