/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from './subjectDto';
import type { GetSubjectById200AllOfMeta } from './getSubjectById200AllOfMeta';

export type GetSubjectById200AllOf = {
  data?: SubjectDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSubjectById200AllOfMeta;
};
