/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { GetSpacesByQuery200AllOfMeta } from './getSpacesByQuery200AllOfMeta';

export type GetSpacesByQuery200AllOf = {
  data?: SpaceDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSpacesByQuery200AllOfMeta;
};
