/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from './subjectDto';
import type { GetSubjectsByQuery200AllOfMeta } from './getSubjectsByQuery200AllOfMeta';

export type GetSubjectsByQuery200AllOf = {
  data?: SubjectDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSubjectsByQuery200AllOfMeta;
};
