/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';
import type { GetSessionsByQuery200AllOfMeta } from './getSessionsByQuery200AllOfMeta';

export type GetSessionsByQuery200AllOf = {
  data?: SessionDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSessionsByQuery200AllOfMeta;
};
