/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';
import type { SessionTypes } from './sessionTypes';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';

export type GetSessionsByQueryParams = {
name?: SortOrder;
timelineId?: string;
tenantId?: string;
type?: SessionTypes;
repeatCycle?: number;
repeatCycleType?: RepeatCycleTypes;
recurringDayOfTheWeek?: RecurringDayOfTheWeek[];
endDate?: string | null;
startDate?: string | null;
id?: string;
createdAtSortOrder?: SortOrder;
skip?: number;
take?: number;
};
