/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';
import type { SessionTypes } from './sessionTypes';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';

export type GetSessionsByQueryParams = {
tenantId?: string;
name?: SortOrder;
tenancyId?: string;
type?: SessionTypes;
repeatCycle?: number;
repeatCycleType?: RepeatCycleTypes;
recurringDayOfTheWeek?: RecurringDayOfTheWeek[];
endDate?: string | null;
baseDate?: string | null;
timelineDates?: string[];
oneTimeDate?: string;
id?: string;
createdAtSortOrder?: SortOrder;
skip?: number;
take?: number;
};
