/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from './subjectDto';
import type { GetSubjectsByPageQuery200AllOfMeta } from './getSubjectsByPageQuery200AllOfMeta';

export type GetSubjectsByPageQuery200AllOf = {
  data?: SubjectDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetSubjectsByPageQuery200AllOfMeta;
};
