/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetSpacesByQueryParams = {
id?: string;
createdAt?: string;
updatedAt?: string;
removedAt?: string | null;
name?: string;
nameSortOrder?: SortOrder;
skip?: number;
take?: number;
};
