/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetTimelineItemsByQueryParams = {
title?: string;
startDateTime?: string;
endDateTime?: string;
timelineId?: string;
description?: string;
address?: string;
maxCapacity?: number;
minCapacity?: number;
tenantId?: string;
id?: string;
nameSortOrder?: SortOrder;
skip?: number;
take?: number;
};
