/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDto } from './tokenDto';
import type { GetToken200AllOfMeta } from './getToken200AllOfMeta';

export type GetToken200AllOf = {
  data?: TokenDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetToken200AllOfMeta;
};
