/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetTemplatesByQueryParams = {
skip?: number;
take?: number;
createdAtSortOrder?: SortOrder;
};
