/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { GetTimelineItem200AllOfMeta } from './getTimelineItem200AllOfMeta';

export type GetTimelineItem200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetTimelineItem200AllOfMeta;
};
