/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';
import type { PostTypes } from './postTypes';
import type { SortOrder } from './sortOrder';

export type GetTemplatesByQueryParams = {
id?: string;
createdAt?: string;
updatedAt?: string;
removedAt?: string | null;
postId?: string;
name?: TemplateNames;
type?: PostTypes;
title?: string;
content?: string;
authorId?: string;
author?: unknown | null;
createdAtSortOrder?: SortOrder;
skip?: number;
take?: number;
};
