/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDto } from './tokenDto';

export type GetToken200AllOf = {
  data?: TokenDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
