/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';

export type GetTemplate200AllOf = {
  data?: TemplateDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
