/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';
import type { GetTemplatesByQuery200AllOfMeta } from './getTemplatesByQuery200AllOfMeta';

export type GetTemplatesByQuery200AllOf = {
  data?: TemplateDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetTemplatesByQuery200AllOfMeta;
};
