/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { GetTimelineItemsByQuery200AllOfMeta } from './getTimelineItemsByQuery200AllOfMeta';

export type GetTimelineItemsByQuery200AllOf = {
  data?: TimelineItemDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetTimelineItemsByQuery200AllOfMeta;
};
