/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineDto } from './timelineDto';
import type { GetTimelinesByQuery200AllOfMeta } from './getTimelinesByQuery200AllOfMeta';

export type GetTimelinesByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: TimelineDto[];
  meta?: GetTimelinesByQuery200AllOfMeta;
};
