/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';

export type GetUser200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: UserDto;
};
