/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { UserClassificationDto } from './userClassificationDto';
import type { GetUserClassificationsByQuery200AllOfMeta } from './getUserClassificationsByQuery200AllOfMeta';

export type GetUserClassificationsByQuery200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: UserClassificationDto[];
  meta?: GetUserClassificationsByQuery200AllOfMeta;
};
