/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { GetUsersByQuery200AllOfMeta } from './getUsersByQuery200AllOfMeta';

export type GetUsersByQuery200AllOf = {
  data?: UserDto[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetUsersByQuery200AllOfMeta;
};
