/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { GetUser200AllOfMeta } from './getUser200AllOfMeta';

export type GetUser200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetUser200AllOfMeta;
};
