/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { AssociationDto } from './associationDto';
import type { TenancyDto } from './tenancyDto';

export interface GroupDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  tenancyId: string;
  serviceId: string;
  service?: ServiceDto;
  associations?: AssociationDto;
  tenancy?: TenancyDto;
}
