/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { AssociationDto } from './associationDto';
import type { TenantDto } from './tenantDto';

export interface GroupDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  label: string;
  serviceId: string;
  tenantId: string;
  service?: ServiceDto;
  associations?: AssociationDto;
  tenant?: TenantDto;
}
