/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDto } from './tokenDto';

export type Login200AllOf = {
  data?: TokenDto;
  message?: string;
  statusCode?: string;
};
