/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface LoginPayloadDto {
  /** @pattern ^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$ */
  email: string;
  /** @pattern ^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$ */
  password: string;
}
