/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { LoginFormDtoSchemaOneOf } from './loginFormDtoSchemaOneOf';
import type { LoginFormDtoSchemaOneOfTwoItem } from './loginFormDtoSchemaOneOfTwoItem';
import type { LoginFormDtoSchemaOneOfThree } from './loginFormDtoSchemaOneOfThree';

export type LoginFormDtoSchema = LoginFormDtoSchemaOneOf | LoginFormDtoSchemaOneOfTwoItem[] | LoginFormDtoSchemaOneOfThree;
