/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export interface LoginDto {
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
}
