/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { MenuDtoChildrenItem } from './menuDtoChildrenItem';
import type { MenuDtoPathname } from './menuDtoPathname';

export interface MenuDto {
  children?: MenuDtoChildrenItem[];
  pathname?: MenuDtoPathname;
  text: string;
}
