/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type MenuDtoChildrenItemPathname = typeof MenuDtoChildrenItemPathname[keyof typeof MenuDtoChildrenItemPathname];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MenuDtoChildrenItemPathname = {
  'admin/userService/users': 'admin/userService/users',
  'admin/userService/users/:id': 'admin/userService/users/:id',
} as const;
