/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { MenuDtoChildrenItemPathname } from './menuDtoChildrenItemPathname';

export type MenuDtoChildrenItem = {
  pathname: MenuDtoChildrenItemPathname;
  text: string;
};
