/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type Order = typeof Order[keyof typeof Order];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Order = {
  asc: 'asc',
  desc: 'desc',
} as const;
