/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type PageTypes = typeof PageTypes[keyof typeof PageTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageTypes = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  TOP_TAB: 'TOP_TAB',
  BUTTON: 'BUTTON',
  MENU: 'MENU',
  LANDING: 'LANDING',
} as const;
