/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface PageDto {
  createdAt: string;
  elementIds: string;
  id: string;
  name: string;
  /** @nullable */
  params?: string | null;
  pathname: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  tenantId: string;
  updatedAt: string;
}
