/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageTypes } from './pageTypes';

export interface PageDto {
  createdAt: string;
  id: string;
  name: string;
  pathname: string;
  /** @nullable */
  removedAt: string | null;
  type: PageTypes;
  updatedAt: string;
}
