/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PartialTypeClassAuthor } from './partialTypeClassAuthor';
import type { PostTypes } from './postTypes';

export interface PartialTypeClass {
  /** @nullable */
  author?: PartialTypeClassAuthor;
  authorId?: string;
  content?: string;
  createdAt?: string;
  id?: string;
  /** @nullable */
  removedAt?: string | null;
  title?: string;
  type?: PostTypes;
  updatedAt?: string;
}
