/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthor } from './postAuthor';
import type { PostTypes } from './postTypes';

export interface Post {
  /** @nullable */
  author?: PostAuthor;
  authorId?: string;
  content?: string;
  createdAt?: string;
  id?: string;
  /** @nullable */
  removedAt?: string | null;
  title?: string;
  type?: PostTypes;
  updatedAt?: string;
}
