/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { PostTypes } from './postTypes';

export interface Post {
  assignemntIds?: string[];
  author?: UserDto;
  authorId?: string;
  classificationId?: string;
  content?: string;
  createdAt?: string;
  description?: string;
  dopotId?: string;
  id?: string;
  /** @nullable */
  removedAt?: string | null;
  seq?: number;
  tenantId?: string;
  title?: string;
  type?: PostTypes;
  updatedAt?: string;
}
