/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type PostTypes = typeof PostTypes[keyof typeof PostTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostTypes = {
  HTML: 'HTML',
  TEXT: 'TEXT',
} as const;
