/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type RecurringDayOfTheWeek = typeof RecurringDayOfTheWeek[keyof typeof RecurringDayOfTheWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecurringDayOfTheWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;
