/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { RemoveAssociations200AllOfMeta } from './removeAssociations200AllOfMeta';

export type RemoveAssociations200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveAssociations200AllOfMeta;
};
