/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';
import type { RemoveTemplates200AllOfMeta } from './removeTemplates200AllOfMeta';

export type RemoveTemplates200AllOf = {
  data?: TemplateDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveTemplates200AllOfMeta;
};
