/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';
import type { RemovePage200AllOfMeta } from './removePage200AllOfMeta';

export type RemovePage200AllOf = {
  data?: PageDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemovePage200AllOfMeta;
};
