/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { RemoveTimelineItem200AllOfMeta } from './removeTimelineItem200AllOfMeta';

export type RemoveTimelineItem200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveTimelineItem200AllOfMeta;
};
