/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { GymDto } from './gymDto';

export type RemoveGymById200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  /** @nullable */
  data?: GymDto;
};
