/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { RemoveClassification200AllOfMeta } from './removeClassification200AllOfMeta';

export type RemoveClassification200AllOf = {
  data?: ClassificationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveClassification200AllOfMeta;
};
