/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AbilityDto } from './abilityDto';

export type RemoveAbility200AllOf = {
  data?: AbilityDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
