/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { Number } from './number';

export type RemoveGroupsByIds200AllOf = {
  data?: Number;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
