/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { DepotDto } from './depotDto';

export type RemoveDepots200AllOf = {
  data?: DepotDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
