/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Number } from './number';
import type { RemoveGroups200AllOfMeta } from './removeGroups200AllOfMeta';

export type RemoveGroups200AllOf = {
  data?: Number;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveGroups200AllOfMeta;
};
