/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { RemoveSpace200AllOfMeta } from './removeSpace200AllOfMeta';

export type RemoveSpace200AllOf = {
  data?: SpaceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveSpace200AllOfMeta;
};
