/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';

export type RemoveTimelineItems200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
