/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { RemoveUser200AllOfMeta } from './removeUser200AllOfMeta';

export type RemoveUser200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveUser200AllOfMeta;
};
