/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';
import type { RemoveSessions200AllOfMeta } from './removeSessions200AllOfMeta';

export type RemoveSessions200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveSessions200AllOfMeta;
};
