/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { RemoveUsers200AllOfMeta } from './removeUsers200AllOfMeta';

export type RemoveUsers200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveUsers200AllOfMeta;
};
