/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type RemoveSpace200AllOfMeta = {
  /** */
  hasNextPage?: boolean;
  /** */
  hasPreviousPage?: boolean;
  /** */
  itemCount?: number;
  /** */
  pageCount?: number;
  /** */
  skip?: number;
  /** */
  take?: number;
};
