/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';

export type RemovePages200AllOf = {
  data?: PageDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
