/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from './sessionDto';
import type { RemoveSession200AllOfMeta } from './removeSession200AllOfMeta';

export type RemoveSession200AllOf = {
  data?: SessionDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveSession200AllOfMeta;
};
