/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { RemoveClassifications200AllOfMeta } from './removeClassifications200AllOfMeta';

export type RemoveClassifications200AllOf = {
  data?: ClassificationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveClassifications200AllOfMeta;
};
