/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { RemoveServices200AllOfMeta } from './removeServices200AllOfMeta';

export type RemoveServices200AllOf = {
  data?: ServiceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveServices200AllOfMeta;
};
