/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { PageDto } from './pageDto';
import type { RemovePages200AllOfMeta } from './removePages200AllOfMeta';

export type RemovePages200AllOf = {
  data?: PageDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemovePages200AllOfMeta;
};
