/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { RemoveAssignment200AllOfMeta } from './removeAssignment200AllOfMeta';

export type RemoveAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveAssignment200AllOfMeta;
};
