/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssociationDto } from './associationDto';
import type { RemoveAssociation200AllOfMeta } from './removeAssociation200AllOfMeta';

export type RemoveAssociation200AllOf = {
  data?: AssociationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: RemoveAssociation200AllOfMeta;
};
