/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type RepeatCycleTypes = typeof RepeatCycleTypes[keyof typeof RepeatCycleTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RepeatCycleTypes = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
  YEAR: 'YEAR',
} as const;
