/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReservationStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
} as const;
