/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntityData } from './responseEntityData';
import type { ResponseEntityHttpStatus } from './responseEntityHttpStatus';
import type { PageMetaDto } from './pageMetaDto';

export interface ResponseEntity {
  /** @nullable */
  data: ResponseEntityData;
  httpStatus: ResponseEntityHttpStatus;
  message: string;
  meta: PageMetaDto;
}
