/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ResponseEntityData = { [key: string]: unknown } | null;
