/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntityData } from './responseEntityData';

export interface ResponseEntity {
  data: ResponseEntityData;
  message: string;
  statusCode: string;
}
