/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';
import type { TenantDto } from './tenantDto';

export interface RoleDto {
  createdAt: string;
  id: string;
  name: Roles;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  tenancyId: string;
  tenant?: TenantDto;
  updatedAt: string;
}
