/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';
import type { TenantDto } from './tenantDto';

export interface RoleDto {
  associationIds: string[];
  /** @nullable */
  classificationId: string | null;
  createdAt: string;
  id: string;
  name: Roles;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  tenant?: TenantDto;
  updatedAt: string;
}
