/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ContentDto } from './contentDto';

export interface RoutineDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  label: string;
  name: string;
  contentId: string;
  content: ContentDto;
}
