/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SystemEmailDto } from './systemEmailDto';

export type SendEmailVerification200AllOf = {
  data?: SystemEmailDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
