/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SystemEmailDto } from './systemEmailDto';
import type { SendEmailVerification200AllOfMeta } from './sendEmailVerification200AllOfMeta';

export type SendEmailVerification200AllOf = {
  data?: SystemEmailDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: SendEmailVerification200AllOfMeta;
};
