/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceDto {
  createdAt: string;
  id: string;
  label: string;
  name: string;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
