/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceFormDtoDefaultObjectName } from './serviceFormDtoDefaultObjectName';

export type ServiceFormDtoDefaultObject = {
  name?: ServiceFormDtoDefaultObjectName;
};
