/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceFormDtoDefaultObject } from './serviceFormDtoDefaultObject';
import type { ServiceFormDtoForm } from './serviceFormDtoForm';
import type { ServiceFormDtoSchema } from './serviceFormDtoSchema';

export interface ServiceFormDto {
  defaultObject: ServiceFormDtoDefaultObject;
  form: ServiceFormDtoForm;
  schema: ServiceFormDtoSchema;
}
