/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceEntityDeletedAt } from './serviceEntityDeletedAt';
import type { ServiceEntityName } from './serviceEntityName';
import type { ServiceEntityUpdatedAt } from './serviceEntityUpdatedAt';

export interface ServiceEntity {
  createdAt: string;
  deletedAt: ServiceEntityDeletedAt;
  id: string;
  name: ServiceEntityName;
  updatedAt: ServiceEntityUpdatedAt;
}
