/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceNames = typeof ServiceNames[keyof typeof ServiceNames];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceNames = {
  USER: 'USER',
  ROLE: 'ROLE',
  SPACE: 'SPACE',
  CONTENT: 'CONTENT',
  TIMELINE: 'TIMELINE',
  FILE: 'FILE',
} as const;
