/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceDto {
  createdAt: string;
  id: string;
  /** @nullable */
  label: string | null;
  name: string;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
