/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceFormDtoFormNameOptionsItemText } from './serviceFormDtoFormNameOptionsItemText';
import type { ServiceFormDtoFormNameOptionsItemValue } from './serviceFormDtoFormNameOptionsItemValue';

export type ServiceFormDtoFormNameOptionsItem = {
  text: ServiceFormDtoFormNameOptionsItemText;
  value: ServiceFormDtoFormNameOptionsItemValue;
};
