/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceName } from './serviceName';

export interface ServiceDto {
  createdAt: string;
  id: string;
  /** @nullable */
  label: string | null;
  name: ServiceName;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
