/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type ServiceFormDtoFormNameOptionsItemText = typeof ServiceFormDtoFormNameOptionsItemText[keyof typeof ServiceFormDtoFormNameOptionsItemText];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceFormDtoFormNameOptionsItemText = {
  설정_서비스: '설정 서비스',
  유저_서비스: '유저 서비스',
} as const;
