/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceNames = typeof ServiceNames[keyof typeof ServiceNames];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceNames = {
  USER: 'USER',
  SPACE: 'SPACE',
  POST: 'POST',
  ROLE: 'ROLE',
  TIMELINE: 'TIMELINE',
  ROUTINE: 'ROUTINE',
} as const;
