/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type ServiceName = typeof ServiceName[keyof typeof ServiceName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceName = {
  USER: 'USER',
  RESERVATION: 'RESERVATION',
} as const;
