/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type ServiceFormDtoFormNameOptionsItemValue = typeof ServiceFormDtoFormNameOptionsItemValue[keyof typeof ServiceFormDtoFormNameOptionsItemValue];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceFormDtoFormNameOptionsItemValue = {
  userService: 'userService',
  settingService: 'settingService',
} as const;
