/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { SessionTypes } from './sessionTypes';

export interface SessionDto {
  createdAt: string;
  endDateTime?: string;
  id: string;
  name: string;
  /** @nullable */
  recurringDayOfWeek?: RecurringDayOfTheWeek;
  /** @nullable */
  recurringMonth?: number | null;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  repeatCycleType?: RepeatCycleTypes;
  seq: number;
  startDateTime?: string;
  /** @nullable */
  timelineId?: string | null;
  type: SessionTypes;
  updatedAt: string;
}
