/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type SessionTypes = typeof SessionTypes[keyof typeof SessionTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionTypes = {
  ONE_TIME: 'ONE_TIME',
  ONE_TIME_RANGE: 'ONE_TIME_RANGE',
  RECURRING: 'RECURRING',
} as const;
