/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpPayloadDto {
  email: string;
  name: string;
  nickname: string;
  password: string;
  phone: string;
  spaceId: string;
}
