/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDto } from './tokenDto';

export type SignUpUser201AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: TokenDto;
};
