/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDto } from './tokenDto';
import type { SignUpUser201AllOfMeta } from './signUpUser201AllOfMeta';

export type SignUpUser201AllOf = {
  data?: TokenDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: SignUpUser201AllOfMeta;
};
