/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { AssociationDto } from './associationDto';

export interface SpaceDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  name: string;
  classification?: ClassificationDto;
  associations?: AssociationDto;
}
