/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';

export interface SpaceDto {
  assignmentIds: string[];
  /** @nullable */
  classificationId: string | null;
  createdAt: string;
  groups?: GroupDto;
  id: string;
  name: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  updatedAt: string;
}
