/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface SubjectDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  tenancyId: string;
  name: string;
}
