/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { EmailStatus } from './emailStatus';

export interface SystemEmailDto {
  createdAt: string;
  emailId: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  status: EmailStatus;
  templateId: string;
  updatedAt: string;
}
