/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';
import type { TemplateDtoPost } from './templateDtoPost';

export interface TemplateDto {
  createdAt: string;
  id: string;
  name: TemplateNames;
  /** @nullable */
  post?: TemplateDtoPost;
  postId: string;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
