/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export type TemplateNames = typeof TemplateNames[keyof typeof TemplateNames];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TemplateNames = {
  WELCOME: 'WELCOME',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  RESET_PASSWORD: 'RESET_PASSWORD',
} as const;
