/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';

/**
 * @nullable
 */
export type TenancyDtoUsers = UserDto | null;
