/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { SpaceDto } from './spaceDto';

export interface TenantDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  roleId: string;
  userId: string;
  spaceId: string;
  user?: UserDto;
  space?: SpaceDto;
}
