/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { UserDto } from './userDto';

export interface TenantDto {
  createdAt: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  roleId: string;
  seq: number;
  space?: SpaceDto;
  spaceId: string;
  updatedAt: string;
  user?: UserDto;
  userId: string;
}
