/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export interface TenancyDto {
  createdAt: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  space: SpaceDto;
  spaceId: string;
  updatedAt: string;
}
