/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TenancyDtoAssociations } from './tenancyDtoAssociations';
import type { TenancyDtoCategories } from './tenancyDtoCategories';
import type { TenancyDtoClassifications } from './tenancyDtoClassifications';
import type { TenancyDtoGroups } from './tenancyDtoGroups';
import type { TenancyDtoSpace } from './tenancyDtoSpace';
import type { TenancyDtoUsers } from './tenancyDtoUsers';

export interface TenancyDto {
  /** @nullable */
  associations: TenancyDtoAssociations;
  /** @nullable */
  categories: TenancyDtoCategories;
  /** @nullable */
  classifications: TenancyDtoClassifications;
  createdAt: string;
  /** @nullable */
  groups: TenancyDtoGroups;
  id: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  /** @nullable */
  space: TenancyDtoSpace;
  spaceId: string;
  updatedAt: string;
  /** @nullable */
  users: TenancyDtoUsers;
}
