/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

/**
 * @nullable
 */
export type TenancyDtoSpace = SpaceDto | null;
