/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';

/**
 * @nullable
 */
export type TenancyDtoCategories = CategoryDto | null;
