/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export type TextTypes = typeof TextTypes[keyof typeof TextTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextTypes = {
  Editor: 'Editor',
  Input: 'Input',
  Textarea: 'Textarea',
} as const;
