/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineDtoTimelineItems } from './timelineDtoTimelineItems';

export interface TimelineDto {
  createdAt: string;
  id: string;
  name: string;
  /** @nullable */
  removedAt: string | null;
  sessionId: string;
  tenantId: string;
  /** @nullable */
  timelineItems: TimelineDtoTimelineItems;
  updatedAt: string;
}
