/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';

export interface TimelineDto {
  createdAt: string;
  date: string;
  id: string;
  /** @nullable */
  removedAt: string | null;
  sessionId: string;
  tenantId: string;
  /** @nullable */
  timelineItem: TimelineItemDto[] | null;
  timelineItemId?: string;
  updatedAt: string;
}
