/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface TimelineDto {
  createdAt: string;
  endDateTime: string;
  id: string;
  name: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  startDateTime: string;
  tenancyId: string;
  tenantId: string;
  updatedAt: string;
}
