/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ReservationDto } from './reservationDto';

export interface TimelineItemDto {
  address: string;
  createdAt: string;
  description: string;
  endDateTime: string;
  id: string;
  maxCapacity: number;
  minCapacity: number;
  /** @nullable */
  removedAt: string | null;
  /** @nullable */
  reservations: ReservationDto[] | null;
  startDateTime: string;
  tenantId: string;
  timelineId?: string;
  title: string;
  updatedAt: string;
}
