/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDtoUserProfilesItemCreatedAt } from './tokenDtoUserProfilesItemCreatedAt';
import type { TokenDtoUserProfilesItemDeletedAt } from './tokenDtoUserProfilesItemDeletedAt';
import type { TokenDtoUserProfilesItemUpdatedAt } from './tokenDtoUserProfilesItemUpdatedAt';

export type TokenDtoUserProfilesItem = {
  createdAt: TokenDtoUserProfilesItemCreatedAt;
  deletedAt: TokenDtoUserProfilesItemDeletedAt;
  id: string;
  nickname: string;
  updatedAt: TokenDtoUserProfilesItemUpdatedAt;
  userId: string;
};
