/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDtoUserTenantsItemUserCreatedAt } from './tokenDtoUserTenantsItemUserCreatedAt';
import type { TokenDtoUserTenantsItemUserDeletedAt } from './tokenDtoUserTenantsItemUserDeletedAt';
import type { TokenDtoUserTenantsItemUserUpdatedAt } from './tokenDtoUserTenantsItemUserUpdatedAt';

export type TokenDtoUserTenantsItemUser = {
  createdAt: TokenDtoUserTenantsItemUserCreatedAt;
  deletedAt: TokenDtoUserTenantsItemUserDeletedAt;
  email: string;
  id: string;
  name: string;
  password: string;
  phone: string;
  updatedAt: TokenDtoUserTenantsItemUserUpdatedAt;
};
