/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDtoUserTenantsItemSpaceCreatedAt } from './tokenDtoUserTenantsItemSpaceCreatedAt';
import type { TokenDtoUserTenantsItemSpaceDeletedAt } from './tokenDtoUserTenantsItemSpaceDeletedAt';
import type { TokenDtoUserTenantsItemSpaceUpdatedAt } from './tokenDtoUserTenantsItemSpaceUpdatedAt';

export type TokenDtoUserTenantsItemSpace = {
  createdAt: TokenDtoUserTenantsItemSpaceCreatedAt;
  deletedAt: TokenDtoUserTenantsItemSpaceDeletedAt;
  id: string;
  name: string;
  updatedAt: TokenDtoUserTenantsItemSpaceUpdatedAt;
};
