/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TokenDtoUserCreatedAt } from './tokenDtoUserCreatedAt';
import type { TokenDtoUserDeletedAt } from './tokenDtoUserDeletedAt';
import type { TokenDtoUserProfilesItem } from './tokenDtoUserProfilesItem';
import type { TokenDtoUserTenantsItem } from './tokenDtoUserTenantsItem';
import type { TokenDtoUserUpdatedAt } from './tokenDtoUserUpdatedAt';

export type TokenDtoUser = {
  createdAt: TokenDtoUserCreatedAt;
  deletedAt: TokenDtoUserDeletedAt;
  email: string;
  id: string;
  name: string;
  password: string;
  phone: string;
  profiles: TokenDtoUserProfilesItem[];
  tenants: TokenDtoUserTenantsItem[];
  updatedAt: TokenDtoUserUpdatedAt;
};
