/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserDto {
  tenancyId?: string;
  spaceId?: string;
  email?: string;
  name?: string;
  phone?: string;
  /** @minLength 6 */
  password?: string;
}
