/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTimelineItemDto {
  address?: string;
  description?: string;
  endDateTime?: string;
  id: string;
  maxCapacity?: number;
  minCapacity?: number;
  startDateTime?: string;
  tenantId?: string;
  timelineId?: string;
  title?: string;
}
