/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';

export type UpdateService200AllOf = {
  data?: ServiceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
