/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateGroupDto {
  createdAt?: string;
  /** @nullable */
  deletedAt?: string | null;
  id?: string;
  /** @nullable */
  updatedAt?: string | null;
}
