/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';
import type { UpdateTemplate200AllOfMeta } from './updateTemplate200AllOfMeta';

export type UpdateTemplate200AllOf = {
  data?: TemplateDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateTemplate200AllOfMeta;
};
