/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCategoryDtoName = typeof UpdateCategoryDtoName[keyof typeof UpdateCategoryDtoName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCategoryDtoName = {
  USER: 'USER',
  SPACE: 'SPACE',
} as const;
