/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineItemDto } from './timelineItemDto';
import type { UpdateTimelineItem200AllOfMeta } from './updateTimelineItem200AllOfMeta';

export type UpdateTimelineItem200AllOf = {
  data?: TimelineItemDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateTimelineItem200AllOfMeta;
};
