/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCategoryDtoDeletedAt } from './updateCategoryDtoDeletedAt';
import type { UpdateCategoryDtoName } from './updateCategoryDtoName';
import type { UpdateCategoryDtoUpdatedAt } from './updateCategoryDtoUpdatedAt';

export interface UpdateCategoryDto {
  createdAt?: string;
  deletedAt?: UpdateCategoryDtoDeletedAt;
  id?: string;
  name?: UpdateCategoryDtoName;
  updatedAt?: UpdateCategoryDtoUpdatedAt;
}
