/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleDto } from './roleDto';

export type UpdateRole200AllOf = {
  data?: RoleDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
