/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateGroupDto {
  name?: string;
  /** @nullable */
  label?: string | null;
  serviceId?: string;
  tenantId?: string;
}
