/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateClassificationDto {
  categoryId?: string;
  /** @nullable */
  depotFileId?: string | null;
  /** @nullable */
  postId?: string | null;
  /** @nullable */
  spaceId?: string | null;
  /** @nullable */
  userId?: string | null;
}
