/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateClassificationDto {
  categoryId?: string;
  /** @nullable */
  postId?: string | null;
  /** @nullable */
  roleId?: string | null;
  /** @nullable */
  routineId?: string | null;
  serviceId?: string;
  /** @nullable */
  spaceId?: string | null;
  tenancyId?: string;
  /** @nullable */
  userId?: string | null;
}
