/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TextTypes } from './textTypes';

export interface UpdateExerciseDto {
  duration?: number;
  count?: number;
  name?: string;
  label?: string;
  title?: string;
  type?: TextTypes;
  description?: string;
  text?: string;
  imageFileIds?: string;
  videoFileId?: string;
}
