/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDto } from './templateDto';

export type UpdateTemplate200AllOf = {
  data?: TemplateDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
