/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSpaceDto {
  assignmentIds?: string[];
  /** @nullable */
  classificationId?: string | null;
  createdAt?: string;
  id?: string;
  name?: string;
  /** @nullable */
  removedAt?: string | null;
  seq?: number;
  updatedAt?: string;
}
