/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateAssociationDto {
  /** @nullable */
  fileId?: string | null;
  /** @nullable */
  contentId?: string | null;
  /** @nullable */
  timelineId?: string | null;
  /** @nullable */
  roleId?: string | null;
  /** @nullable */
  groupId?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  spaceId?: string | null;
  /** @nullable */
  postId?: string | null;
  serviceId?: string;
}
