/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type UpdateServiceDtoName = typeof UpdateServiceDtoName[keyof typeof UpdateServiceDtoName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServiceDtoName = {
  USER: 'USER',
  SPACE: 'SPACE',
} as const;
