/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSpaceDto } from './createSpaceDto';

export interface UpdateGymDto {
  name?: string;
  label?: string;
  businessNo?: string;
  address?: string;
  phone?: string;
  email?: string;
  businessNumber?: string;
  depotId?: string;
  categoryId?: string;
  space?: CreateSpaceDto;
}
