/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateServiceDtoDeletedAt } from './updateServiceDtoDeletedAt';
import type { UpdateServiceDtoName } from './updateServiceDtoName';
import type { UpdateServiceDtoUpdatedAt } from './updateServiceDtoUpdatedAt';

export interface UpdateServiceDto {
  createdAt?: string;
  deletedAt?: UpdateServiceDtoDeletedAt;
  id?: string;
  name?: UpdateServiceDtoName;
  updatedAt?: UpdateServiceDtoUpdatedAt;
}
