/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';

export type UpdateGroup200AllOf = {
  data?: GroupDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
