/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRoutineDtoType } from './updateRoutineDtoType';

export interface UpdateRoutineDto {
  name?: string;
  tenancyId?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  type?: UpdateRoutineDtoType;
  /** @nullable */
  text?: string | null;
}
