/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */

/**
 * A JSON object with a nested structure
 */
export type UpdateAbilityDtoConditions = { [key: string]: unknown };
