/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';
import type { UpdateSpace200AllOfMeta } from './updateSpace200AllOfMeta';

export type UpdateSpace200AllOf = {
  data?: SpaceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateSpace200AllOfMeta;
};
