/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateExerciseDto {
  name?: string;
  description?: string;
  imageDepotId?: string;
  videoDepotId?: string;
  duration?: number;
  count?: number;
  tenantId?: string;
}
