/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { GroupDto } from './groupDto';
import type { UpdateGroup200AllOfMeta } from './updateGroup200AllOfMeta';

export type UpdateGroup200AllOf = {
  data?: GroupDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateGroup200AllOfMeta;
};
