/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

/**
 * Service name
 */
export type UpdateServiceDtoName = typeof UpdateServiceDtoName[keyof typeof UpdateServiceDtoName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServiceDtoName = {
  userService: 'userService',
  settingService: 'settingService',
} as const;
