/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SpaceDto } from './spaceDto';

export type UpdateSpace200AllOf = {
  data?: SpaceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
