/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDto } from './serviceDto';
import type { UpdateService200AllOfMeta } from './updateService200AllOfMeta';

export type UpdateService200AllOf = {
  data?: ServiceDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateService200AllOfMeta;
};
