/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSpaceDto {
  label?: string;
  name?: string;
  categoryId?: string;
  serviceId?: string;
}
