/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserDtoPost } from './updateUserDtoPost';
import type { UserDto } from './userDto';

export interface UpdateUserDto {
  assignmentIds?: string[];
  /** @nullable */
  classificationId?: string | null;
  email?: string;
  name?: string;
  /** @minLength 6 */
  password?: string;
  phone?: string;
  /** @nullable */
  post?: UpdateUserDtoPost;
  spaceId?: string;
  /** @nullable */
  tenantId?: string | null;
  user?: UserDto;
}
