/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from './subjectDto';

export type UpdateSubjectById200AllOf = {
  data?: SubjectDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
};
