/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryTypes } from './categoryTypes';

export interface UpdateCategoryDto {
  ancestorIds?: string[];
  createdAt?: string;
  id?: string;
  name?: string;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  removedAt?: string | null;
  seq?: number;
  serviceId?: string;
  tenantId?: string;
  type?: CategoryTypes;
  updatedAt?: string;
}
