/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { File } from './file';

export interface UpdateDepotDto {
  files: File[];
  name?: string;
}
