/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';

export interface UpdateRoleDto {
  tenantId?: string;
  name?: Roles;
  serviceId?: string;
  categoryId?: string;
}
