/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryDto {
  ancestorIds?: string[];
  createdAt?: string;
  deletedAt?: string | null;
  id?: string;
  name?: string;
  parentId?: string | null;
  serviceId?: string;
  spaceId?: string;
  updatedAt?: string | null;
}
