/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';
import type { UpdateTemplateDtoPost } from './updateTemplateDtoPost';

export interface UpdateTemplateDto {
  name?: TemplateNames;
  /** @nullable */
  post?: UpdateTemplateDtoPost;
}
