/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDto } from './classificationDto';
import type { UpdateClassification200AllOfMeta } from './updateClassification200AllOfMeta';

export type UpdateClassification200AllOf = {
  data?: ClassificationDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateClassification200AllOfMeta;
};
