/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentDto } from './assignmentDto';
import type { UpdateAssignment200AllOfMeta } from './updateAssignment200AllOfMeta';

export type UpdateAssignment200AllOf = {
  data?: AssignmentDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateAssignment200AllOfMeta;
};
