/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { SessionTypes } from './sessionTypes';

export interface UpdateSessionDto {
  createdAt?: string;
  endTime?: string;
  id?: string;
  name?: string;
  recurringDayOfTheWeek?: RecurringDayOfTheWeek;
  /** @nullable */
  removedAt?: string | null;
  repeatCycle?: number;
  repeatCycleType?: RepeatCycleTypes;
  seq?: number;
  startTime?: string;
  timelineId?: string;
  type?: SessionTypes;
  updatedAt?: string;
}
