/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { SessionTypes } from './sessionTypes';
import type { UpdateSessionDtoRepeatCycleType } from './updateSessionDtoRepeatCycleType';
import type { UpdateSessionDtoRecurringDayOfWeek } from './updateSessionDtoRecurringDayOfWeek';

export interface UpdateSessionDto {
  id?: string;
  seq?: number;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  removedAt?: string | null;
  name?: string;
  type?: SessionTypes;
  startDateTime?: string;
  endDateTime?: string;
  /** @nullable */
  timelineId?: string | null;
  /** @nullable */
  repeatCycleType?: UpdateSessionDtoRepeatCycleType;
  /** @nullable */
  recurringDayOfWeek?: UpdateSessionDtoRecurringDayOfWeek;
  /** @nullable */
  recurringMonth?: number | null;
}
