/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { RecurringDayOfTheWeek } from './recurringDayOfTheWeek';
import type { RepeatCycleTypes } from './repeatCycleTypes';
import type { SessionTypes } from './sessionTypes';

export interface UpdateSessionDto {
  /** @nullable */
  endDate?: string | null;
  id: string;
  name?: string;
  recurringDayOfTheWeek?: RecurringDayOfTheWeek[];
  repeatCycle?: number;
  repeatCycleType?: RepeatCycleTypes;
  /** @nullable */
  startDate?: string | null;
  tenantId?: string;
  timelineDates?: string[];
  type?: SessionTypes;
}
