/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramDto } from './programDto';

export type UpdateProgram200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  /** @nullable */
  data?: ProgramDto;
};
