/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserDtoPost } from './updateUserDtoPost';

export interface UpdateUserDto {
  email?: string;
  name?: string;
  /** @minLength 6 */
  password?: string;
  phone?: string;
  /** @nullable */
  post?: UpdateUserDtoPost;
}
