/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from './subjectDto';
import type { UpdateSubjectById200AllOfMeta } from './updateSubjectById200AllOfMeta';

export type UpdateSubjectById200AllOf = {
  data?: SubjectDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateSubjectById200AllOfMeta;
};
