/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';
import type { UpdateUser200AllOfMeta } from './updateUser200AllOfMeta';

export type UpdateUser200AllOf = {
  data?: UserDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: UpdateUser200AllOfMeta;
};
