/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoTenantsItemSpaceCreatedAt } from './userDtoTenantsItemSpaceCreatedAt';
import type { UserDtoTenantsItemSpaceDeletedAt } from './userDtoTenantsItemSpaceDeletedAt';
import type { UserDtoTenantsItemSpaceUpdatedAt } from './userDtoTenantsItemSpaceUpdatedAt';

export type UserDtoTenantsItemSpace = {
  createdAt: UserDtoTenantsItemSpaceCreatedAt;
  deletedAt: UserDtoTenantsItemSpaceDeletedAt;
  id: string;
  name: string;
  updatedAt: UserDtoTenantsItemSpaceUpdatedAt;
};
