/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoTenantsItemCreatedAt } from './userDtoTenantsItemCreatedAt';
import type { UserDtoTenantsItemDeletedAt } from './userDtoTenantsItemDeletedAt';
import type { UserDtoTenantsItemUpdatedAt } from './userDtoTenantsItemUpdatedAt';

export type UserDtoTenantsItem = {
  createdAt: UserDtoTenantsItemCreatedAt;
  deletedAt: UserDtoTenantsItemDeletedAt;
  id: string;
  roleId: string;
  spaceId: string;
  updatedAt: UserDtoTenantsItemUpdatedAt;
  userId: string;
};
