/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileDto } from './profileDto';
import type { TenantDto } from './tenantDto';

export interface UserDto {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  email: string;
  id: string;
  name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  profiles: ProfileDto[];
  tenants: TenantDto[];
  updatedAt: string;
}
