/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoCreatedAt } from './userDtoCreatedAt';
import type { UserDtoDeletedAt } from './userDtoDeletedAt';
import type { UserDtoProfilesItem } from './userDtoProfilesItem';
import type { UserDtoTenantsItem } from './userDtoTenantsItem';
import type { UserDtoUpdatedAt } from './userDtoUpdatedAt';

export interface UserDto {
  createdAt: UserDtoCreatedAt;
  deletedAt: UserDtoDeletedAt;
  email: string;
  id: string;
  name: string;
  password: string;
  phone: string;
  profiles: UserDtoProfilesItem[];
  tenants: UserDtoTenantsItem[];
  updatedAt: UserDtoUpdatedAt;
}
