/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoTenantsItemSpace } from './userDtoTenantsItemSpace';
import type { UserDtoTenantsItemUser } from './userDtoTenantsItemUser';

export type UserDtoTenantsItem = {
  space: UserDtoTenantsItemSpace;
  user: UserDtoTenantsItemUser;
};
