/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoTenantsItemUserCreatedAt } from './userDtoTenantsItemUserCreatedAt';
import type { UserDtoTenantsItemUserDeletedAt } from './userDtoTenantsItemUserDeletedAt';
import type { UserDtoTenantsItemUserUpdatedAt } from './userDtoTenantsItemUserUpdatedAt';

export type UserDtoTenantsItemUser = {
  createdAt: UserDtoTenantsItemUserCreatedAt;
  deletedAt: UserDtoTenantsItemUserDeletedAt;
  email: string;
  id: string;
  name: string;
  password: string;
  phone: string;
  updatedAt: UserDtoTenantsItemUserUpdatedAt;
};
