/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  createdAt: string;
  email: string;
  id: string;
  name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  /** @nullable */
  removedAt: string | null;
  seq: number;
  spaceId: string;
  tenancyId: string;
  updatedAt: string;
}
