/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Galaxy Server
 * OpenAPI spec version: 1.0.0
 */
import type { SystemEmailDto } from './systemEmailDto';
import type { VerifyEmail200AllOfMeta } from './verifyEmail200AllOfMeta';

export type VerifyEmail200AllOf = {
  data?: SystemEmailDto;
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: VerifyEmail200AllOfMeta;
};
