export enum Pathnames {
  ADMIN_PATH = 'admin',
  DASHBOARD_PAGE_PATH = 'dashboard',
  ADMIN_AUTH_PATH = 'auth',
  ADMIN_AUTH_LOGIN_PATH = 'auth/login',
  ADMIN_MAIN_PATH = 'admin/main',
  ADMIN_SERVICE_PATH = 'main/services/:serviceId',
  ADMIN_SERVICES_PATH = 'main/services',
  ADMIN_SERVICE_SPACES_PATH = 'main/services/:serviceId/spaces',
  ADMIN_SERVICE_SPACE_PATH = 'main/services/:serviceId/spaces/:spaceId',
  ADMIN_SERVICE_SPACE_EDIT_PATH = 'main/services/:serviceId/spaces/:spaceId/edit',
  ADMIN_SERVICE_TIMELINE_ITEMS_PATH = 'main/services/:serviceId/timelineItems',
  ADMIN_SERVICE_TIMELINE_ITEM_PATH = 'main/services/:serviceId/timelineItems/:timelineItemId',
  ADMIN_SERVICE_TIMELINE_ITEM_EDIT_PATH = 'main/services/:serviceId/timelineItems/:timelineItemId/edit',
  ADMIN_SERVICE_SESSIONS_PATH = 'main/services/:serviceId/sessions',
  ADMIN_SERVICE_SESSION_PATH = 'main/services/:serviceId/sessions/:sessionId',
  ADMIN_SERVICE_SESSION_EDIT_PATH = 'main/services/:serviceId/sessions/:sessionId/edit',
  ADMIN_SERVICE_TEMPLATES_PATH = 'main/services/:serviceId/templates',
  ADMIN_SERVICE_TEMPLATE_PATH = 'main/services/:serviceId/templates/:templateId',
  ADMIN_SERVICE_TEMPLATE_EDIT_PATH = 'main/services/:serviceId/templates/:templateId/edit',
  ADMIN_USER_CATEGORIES_PATH = 'main/services/:serviceId/categories',
  ADMIN_USER_GROUPS_PATH = 'main/services/:serviceId/groups',
  ADMIN_USER_CATEGORY_PATH = 'main/services/:serviceId/categories/:categoryId',
  ADMIN_USER_CATEGORY_EDIT_PATH = 'main/services/:serviceId/categories/:categoryId/edit',
}
