/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { FileDto } from './fileDto';

export interface FileClassificationDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  fileId: string;
  categoryId: string;
  category?: CategoryDto;
  file?: FileDto;
}
