/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from './tenantDto';
import type { FileClassificationDto } from './fileClassificationDto';

export interface FileDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  parentId: string;
  tenantId: string;
  name: string;
  size: number;
  mimeType: string;
  url: string;
  tenant?: TenantDto;
  classification?: FileClassificationDto;
}
