/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

import type { GetGroupsByQuery200AllOfMeta } from "./getGroupsByQuery200AllOfMeta";
import type { GroupDto } from "./groupDto";

export type GetGroupsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: GroupDto[];
	meta?: GetGroupsByQuery200AllOfMeta;
};
