/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { SubjectDto } from "./subjectDto";
import type { GetSubjectsByQuery200AllOfMeta } from "./getSubjectsByQuery200AllOfMeta";

export type GetSubjectsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: SubjectDto[];
	meta?: GetSubjectsByQuery200AllOfMeta;
};
