/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export type GetSpaceClassificationsByQuery200AllOfMeta = {
  /** */
  skip?: number;
  /** */
  take?: number;
  /** */
  itemCount?: number;
  /** */
  pageCount?: number;
  /** */
  hasNextPage?: boolean;
  /** */
  hasPreviousPage?: boolean;
};
