/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

import type { GetSpaceClassificationsByQuery200AllOfMeta } from "./getSpaceClassificationsByQuery200AllOfMeta";
import type { SpaceClassificationDto } from "./spaceClassificationDto";

export type GetSpaceClassificationsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: SpaceClassificationDto[];
	meta?: GetSpaceClassificationsByQuery200AllOfMeta;
};
