/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

import type { GetSessionsByQuery200AllOfMeta } from "./getSessionsByQuery200AllOfMeta";
import type { SessionDto } from "./sessionDto";

export type GetSessionsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: SessionDto[];
	meta?: GetSessionsByQuery200AllOfMeta;
};
