/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

import type { GetTimelinesByQuery200AllOfMeta } from "./getTimelinesByQuery200AllOfMeta";
import type { TimelineDto } from "./timelineDto";

export type GetTimelinesByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: TimelineDto[];
	meta?: GetTimelinesByQuery200AllOfMeta;
};
