/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from './sortOrder';

export type GetUsersByQueryParams = {
/**
 * @minimum 1
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 50
 */
take?: number;
createdAtSortOrder?: SortOrder;
};
