/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export type GroupTypes = (typeof GroupTypes)[keyof typeof GroupTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupTypes = {
	Role: "Role",
	Space: "Space",
	File: "File",
	User: "User",
} as const;
