/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntityHttpStatus } from './responseEntityHttpStatus';
import type { ResponseEntityData } from './responseEntityData';
import type { ResponseEntityMeta } from './responseEntityMeta';

export interface ResponseEntity {
  httpStatus: ResponseEntityHttpStatus;
  message: string;
  data?: ResponseEntityData;
  /** @nullable */
  meta?: ResponseEntityMeta;
}
