/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from './categoryDto';
import type { RoleDto } from './roleDto';

export interface RoleClassificationDto {
  id: string;
  seq: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  roleId: string;
  categoryId: string;
  category?: CategoryDto;
  role?: RoleDto;
}
