/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export type Roles = (typeof Roles)[keyof typeof Roles];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Roles = {
	USER: "USER",
	SUPER_ADMIN: "SUPER_ADMIN",
	ADMIN: "ADMIN",
} as const;
