/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

import type { ActivityDto } from "./activityDto";
import type { ExerciseDto } from "./exerciseDto";

export interface TaskDto {
	id: string;
	seq: number;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	tenantId: string;
	exercise: ExerciseDto;
	activities: ActivityDto[];
}
