/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';

export interface UpdateRoleDto {
  name?: Roles;
  serviceId?: string;
  categoryId?: string;
}
