/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryTypes } from "./categoryTypes";

export interface UpdateCategoryDto {
	tenantId?: string;
	name?: string;
	type?: CategoryTypes;
	/** @nullable */
	parentId?: string | null;
}
