/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export type CategoryTypes = (typeof CategoryTypes)[keyof typeof CategoryTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryTypes = {
	Role: "Role",
	Space: "Space",
	File: "File",
	User: "User",
} as const;
