/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGroundDto {
	name: string;
	/** @nullable */
	label?: string | null;
	address: string;
	phone: string;
	email: string;
	businessNo: string;
	/** @nullable */
	logoImageFileId?: string | null;
	/** @nullable */
	imageFileId?: string | null;
	spaceId: string;
}
