/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineDto } from "./timelineDto";

export type DeleteTimeline200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	/** @nullable */
	data?: TimelineDto;
};
