/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { TaskDto } from "./taskDto";

export interface ExerciseDto {
	id: string;
	seq: number;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	duration: number;
	count: number;
	taskId: string;
	description?: string;
	imageFileId?: string;
	videoFileId?: string;
	name: string;
	task: TaskDto;
}
