/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from "./categoryDto";

export type GetCategoryById200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	/** @nullable */
	data?: CategoryDto;
};
