/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 쿠키 기반 JWT 인증이 필요합니다. (@Public 데코레이터가 있는 엔드포인트는 예외)
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from "./sessionDto";
import type { GetSessionsByQuery200AllOfMeta } from "./getSessionsByQuery200AllOfMeta";

export type GetSessionsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: SessionDto[];
	meta?: GetSessionsByQuery200AllOfMeta;
};
