/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDto } from "./sessionDto";

export type GetSession200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	/** @nullable */
	data?: SessionDto;
};
