/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from "./tenantDto";
import type { GetTenantsByQuery200AllOfMeta } from "./getTenantsByQuery200AllOfMeta";

export type GetTenantsByQuery200AllOf = {
	/** */
	httpStatus?: number;
	/** */
	message?: string;
	data?: TenantDto[];
	meta?: GetTenantsByQuery200AllOfMeta;
};
