/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 쿠키 기반 JWT 인증이 필요합니다. (@Public 데코레이터가 있는 엔드포인트는 예외)
 * OpenAPI spec version: 1.0.0
 */

export type GroupTypes = (typeof GroupTypes)[keyof typeof GroupTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupTypes = {
	Role: "Role",
	Space: "Space",
	File: "File",
	User: "User",
} as const;
