/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export type RepeatCycleTypes =
	(typeof RepeatCycleTypes)[keyof typeof RepeatCycleTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RepeatCycleTypes = {
	WEEKLY: "WEEKLY",
	MONTHLY: "MONTHLY",
} as const;
