/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramDto } from "./programDto";
import type { ActivityDto } from "./activityDto";

export interface RoutineDto {
	id: string;
	seq: number;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	name: string;
	label: string;
	programs: ProgramDto[];
	activities: ActivityDto[];
}
