/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Plate
 * OpenAPI spec version: 1.0.0
 */

export interface RouteDto {
	name: string;
	relativePath: string;
	fullPath: string;
	/** @nullable */
	icon: string | null;
	/** @nullable */
	children: RouteDto[] | null;
}
