query GetCategoryItems(
  $skip: Int
  $take: Int
  $sortingKey: String
  $sortingValue: String
) {
  categoryItems(
    skip: $skip
    take: $take
    sortingKey: $sortingKey
    sortingValue: $sortingValue
  ) {
    nodes {
      name
    }
    pageInfo {
      endCursor
      totalCount
    }
  }
}
