export * from './login.route';
export * from './category.route';
export * from './category-add.route';
export * from './category-edit.route';
export * from './groups.route';
export * from './group-edit.route';
export * from './group.route';
export * from './routine-edit.route';
export * from './routines.route';
